### ISSUE TITLE
read_hdf fails in dask even though it works in pandas

### ISSUE THREAD

**Issue by davclark** [dask/dask#1174]
dask version 0.9.0, pandas 0.18.1 (most recent from conda as of posting)

Grab a 1 MB fake TAQ file from [here](https://github.com/dlab-projects/marketflow/raw/master/test-data/small_test_data_public.h5). (aside: same data is ~1/4 MB in zipped fixed width - chunk sizes are probably dumb for this data.)

`pd.read_hdf('small_test_data_public.h5', '/IXQAJE/no_suffix')` works, `dask.dataframe.read_hdf('small_test_data_public.h5', '/IXQAJE/no_suffix')` fails with the following stack trace. I think it may be due to the attempt to read an empty dataframe of 0-length. If I read the intent correctly, it would probably make more sense to retrieve a pytables or h5py object which would provide the desired metadata without the weirdness around a 0-length read.

```
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-110-8ad7ff0d4733> in <module>()
----> 1 spy_dd = dd.read_hdf(fname, max_sym)

/home/dav/miniconda3/envs/TAQ/lib/python3.5/site-packages/dask/dataframe/io.py in read_hdf(pattern, key, start, stop, columns, chunksize, lock)
    559                                     columns=columns, chunksize=chunksize,
    560                                     lock=lock)
--> 561                    for path in paths])
    562 
    563 

/home/dav/miniconda3/envs/TAQ/lib/python3.5/site-packages/dask/dataframe/io.py in <listcomp>(.0)
    559                                     columns=columns, chunksize=chunksize,
    560                                     lock=lock)
--> 561                    for path in paths])
    562 
    563 

/home/dav/miniconda3/envs/TAQ/lib/python3.5/site-packages/dask/dataframe/io.py in _read_single_hdf(path, key, start, stop, columns, chunksize, lock)
    499     from .multi import concat
    500     return concat([one_path_one_key(path, k, start, s, columns, chunksize, lock)
--> 501                    for k, s in zip(keys, stops)])
    502 
    503 

/home/dav/miniconda3/envs/TAQ/lib/python3.5/site-packages/dask/dataframe/io.py in <listcomp>(.0)
    499     from .multi import concat
    500     return concat([one_path_one_key(path, k, start, s, columns, chunksize, lock)
--> 501                    for k, s in zip(keys, stops)])
    502 
    503 

/home/dav/miniconda3/envs/TAQ/lib/python3.5/site-packages/dask/dataframe/io.py in one_path_one_key(path, key, start, stop, columns, chunksize, lock)
    474         not contain any wildcards).
    475         """
--> 476         empty = pd.read_hdf(path, key, stop=0)
    477         if columns is not None:
    478             empty = empty[columns]

/home/dav/miniconda3/envs/TAQ/lib/python3.5/site-packages/pandas/io/pytables.py in read_hdf(path_or_buf, key, **kwargs)
    328                                  'multiple datasets.')
    329             key = keys[0]
--> 330         return store.select(key, auto_close=auto_close, **kwargs)
    331     except:
    332         # if there is an error, close the store

/home/dav/miniconda3/envs/TAQ/lib/python3.5/site-packages/pandas/io/pytables.py in select(self, key, where, start, stop, columns, iterator, chunksize, auto_close, **kwargs)
    678                            chunksize=chunksize, auto_close=auto_close)
    679 
--> 680         return it.get_result()
    681 
    682     def select_as_coordinates(

/home/dav/miniconda3/envs/TAQ/lib/python3.5/site-packages/pandas/io/pytables.py in get_result(self, coordinates)
   1362 
   1363         # directly return the result
-> 1364         results = self.func(self.start, self.stop, where)
   1365         self.close()
   1366         return results

/home/dav/miniconda3/envs/TAQ/lib/python3.5/site-packages/pandas/io/pytables.py in func(_start, _stop, _where)
    671             return s.read(start=_start, stop=_stop,
    672                           where=_where,
--> 673                           columns=columns, **kwargs)
    674 
    675         # create the iterator

/home/dav/miniconda3/envs/TAQ/lib/python3.5/site-packages/pandas/io/pytables.py in read(self, where, columns, **kwargs)
   4052 
   4053             block = make_block(values, placement=np.arange(len(cols_)))
-> 4054             mgr = BlockManager([block], [cols_, index_])
   4055             frames.append(DataFrame(mgr))
   4056 

/home/dav/miniconda3/envs/TAQ/lib/python3.5/site-packages/pandas/core/internals.py in __init__(self, blocks, axes, do_integrity_check, fastpath)
   2592 
   2593         if do_integrity_check:
-> 2594             self._verify_integrity()
   2595 
   2596         self._consolidate_check()

/home/dav/miniconda3/envs/TAQ/lib/python3.5/site-packages/pandas/core/internals.py in _verify_integrity(self)
   2802         for block in self.blocks:
   2803             if block._verify_integrity and block.shape[1:] != mgr_shape[1:]:
-> 2804                 construction_error(tot_items, block.shape[1:], self.axes)
   2805         if len(self.items) != tot_items:
   2806             raise AssertionError('Number of manager items must equal union of '

/home/dav/miniconda3/envs/TAQ/lib/python3.5/site-packages/pandas/core/internals.py in construction_error(tot_items, block_shape, axes, e)
   3966         raise e
   3967     if block_shape[0] == 0:
-> 3968         raise ValueError("Empty data passed with indices specified.")
   3969     raise ValueError("Shape of passed values is {0}, indices imply {1}".format(
   3970         passed, implied))

ValueError: Empty data passed with indices specified.
```

**Comment by mrocklin** [comment]
I believe that this is a repeat of https://github.com/dask/dask/issues/1167

Generally HDF files created with `format="fixed"` can not be easily broken apart by any tool.

**Comment by davclark** [comment]
While these were created with PyTables, from Pandas' point of view, they are 'table' format. If you look in the file I sent, the tables should be easy to read with multiple back-ends. h5py works, for example. The only thing that's exotic maybe is I used blosc compression.

**Comment by mrocklin** [comment]
The problem is that this fails:

```python
In [1]: import pandas as pd

In [2]: pd.read_hdf('small_test_data_public.h5', '/IXQAJE/no_suffix', start=0, stop=1)
ValueError: Shape of passed values is (1, 1), indices imply (1, 915)
```

Can you suggest a different way of pulling out pieces of this table using pandas?  In order to do parallel and chunked reads we need to be able to pull out rows `n` to `n + k`

**Comment by davclark** [comment]
That is very strange... but this works:

```
node = taq_tb.get_node(max_sym)
pd.DataFrame.from_records(node[0:1])
```

And that is about ~200 times faster than reading the whole thing in a similar fashion (like so):

```
node = taq_tb.get_node(max_sym)
pd.DataFrame.from_records(node)
```

But that latter stanza is not quite 10 times slower than reading the whole thing `pd.read_hdf(fname, max_sym)`, implying that your current solution may be generally almost 10 times faster than my proposed solution. h5py is slower than pytables here (strangely, it is faster with numpy operations).

But I still have evidence that the table *can* be read partially (my first stanza is still ~30 times faster than the full `pd.DataFrame.from_records()` solution - and I know 30*10 != 200, but I'm rounding heavily).

**Comment by mrocklin** [comment]
OK, that's a nice route to a solution in this case.  

@jreback any chance I can push this onto Pandas to support `stop=` in these files?  If so I'll raise an issue.  

Generally I'm always a bit hesitant to write any code that doesn't just use the Pandas function.  Historically this has lead to slight differences between dask.dataframe and pandas and results in a large amount of maintenance work as we try to handle a large number of little corner cases.

**Comment by jreback** [comment]
I can fix this: https://github.com/pydata/pandas/issues/8287 and then this will work. not very difficult.

**Comment by davclark** [comment]
@jreback I'm still a bit confused, as I created this file with pytables, which IIUC is similar to the pandas 'tables' format, modulo some attributes, handling of indices, etc. Is there anything I should be doing when I write files with pytables? Or should I just use pandas? (I saw it as an unnecessary dependency on that part of the pipeline, but anyone doing financial data analysis right now should have pandas installed.)

**Comment by jreback** [comment]
reading a PyTables file is done as if it's fixed format, which is fine
but I never implemented start/stop on fixed tables
that's the difficulty here

**Comment by jreback** [comment]
@davclark try with this PR: https://github.com/pydata/pandas/pull/13267

```
In [4]: df = DataFrame({'A' : np.arange(20)})

In [6]: df.to_hdf('test.h5','df',format='fixed')

In [7]: pd.read_hdf('test.h5','df')
Out[7]: 
     A
0    0
1    1
2    2
3    3
4    4
5    5
6    6
7    7
8    8
9    9
10  10
11  11
12  12
13  13
14  14
15  15
16  16
17  17
18  18
19  19

In [8]: pd.read_hdf('test.h5','df',start=10,stop=15)
Out[8]: 
     A
10  10
11  11
12  12
13  13
14  14

In [9]: with pd.HDFStore('test.h5') as store:
   ...:     print(store)
   ...:     
<class 'pandas.io.pytables.HDFStore'>
File path: test.h5
/df            frame        (shape->[20,1])
```

**Comment by davclark** [comment]
Sorry to be so slow in getting back to y'all on this. I just drove to Baltimore where I'll be working mostly on interventions for kids with developmental challenges as opposed to "Other People's Research" (note visual similarity of OPR to OPP).

That said, I'm sure I'll be using this suite of tools.

In the meantime, @deniederhut is doing some work with these TAQ data and I wanted to loop him into this thread.

**Comment by jcrist** [comment]
Should be fixed by pydata/pandas#13267. Closing.

**Comment by DavidLP** [comment]
The error is still there in `dask 0.15.2` and `pandas  0.20.3`. This issued should be reopened.
Minimum Example:
```python
import urllib
import dask.dataframe as df
import pandas as pd

urllib.urlretrieve("https://github.com/dlab-projects/marketflow/raw/master/test-data/small_test_data_public.h5",
                   "small_test_data_public.h5")
pd.read_hdf(r'small_test_data_public.h5',
            '/IXQAJE/no_suffix')
df.read_hdf(r'small_test_data_public.h5',
            '/IXQAJE/no_suffix')
```

gives still:
`ValueError: Empty data passed with indices specified.
`

**Comment by jackdbd** [comment]
I have the same issue.

Here is my environment:
`Python 3.5.2`
`pandas (0.21.1)`
`dask (0.16.0)`

Note: I replaced `urllib.urlretrieve` with `urllib.request.urlretrieve`.

**Comment by clang4** [comment]
I also have the same issue.
Pandas 0.23.4 still seems to have this problem:
`pd.read_hdf('test.h5', '/some_table', start=0, stop=1)`
yields
`ValueError: Shape of passed values is (1, 1), indices imply (1, 153)`
