### ISSUE TITLE
read_csv from S3 times out

### ISSUE THREAD

**Issue by hussainsultan** [dask/dask#1178]
```python
data = dask.dataframe.read_csv('s3://test/test.csv')
```
times out with
```python
ConnectTimeout: HTTPSConnectionPool(host='sts.amazonaws.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<botocore.awsrequest.AWSHTTPSConnection object at 0x7f999ca2c790>, 'Connection to sts.amazonaws.com timed out. (connect timeout=60)'))
```
however, the following works:

```python
import s3fs
fs = s3fs.S3FileSystem()
fs.ls('test')
```

I am on ec2 instance which has an IAM role attached with `S3FullAccess`

**Comment by martindurant** [comment]
Do you know if you are generally able to access sts? You could try `fs.get_delegated_s3pars()` and see if you get the timeout.

I recently made a change to `S3FileSystem(anon=None)` which calls sts to test if boto3 can connect non-anonymously. Is this timeout something you are seeing only recently, or is this the first time you tried to do this? The check could be removed when credentials are supplied.

dask.dataframe.read_csv also calls sts in order to distribute credentials as a delegated token instead of the original raw credentials. The manner in which credentials are circulated (or not) could be made configurable.

**Comment by hussainsultan** [comment]
@martindurant Since the IAM role is attached to my EC2, instance `boto3` is able to get the credentials automatically ( i believe there is an api endpoint that the instance hits to get the creds). However, since there is no user/role when calling STS from ec2 instance, i will not be able to access STS. Per http://boto3.readthedocs.io/en/latest/reference/services/sts.html

> You cannot call Assumerole by using AWS account credentials; access will be denied. You must use IAM user credentials to call AssumeRole.

**Comment by hussainsultan** [comment]
Also, distributing credentials is unsafe and i believe the recommended way is to use IAM role that can be attached to EC2 instances. See :http://docs.aws.amazon.com/IAM/latest/UserGuide/id_roles_use_switch-role-ec2.html

> Instead, you can and should use an IAM role to manage temporary credentials for applications that run on an EC2 instance.

**Comment by hussainsultan** [comment]
fs.get_delegated_s3pars()
```python
ClientError: An error occurred (AccessDenied) when calling the GetSessionToken operation: Cannot call GetSessionToken with session credentials

```

**Comment by martindurant** [comment]
For your case, does `S3FileSystem(anon=True)` still allow you to list/access your keys?
Do you know of a way that I can check whether boto3 has picked up an IAM role configuration?

**Comment by hussainsultan** [comment]
```python
import s3fs
fs = s3fs.S3FileSystem(anon=True)
fs.ls(xxx')
```
gives

```FileNotFoundError: xxx```

**Comment by martindurant** [comment]
Is 'xxx' a existing bucket? Above you were using 'test'.

**Comment by hussainsultan** [comment]
yes! sorry i was trying to be anonymize my logs. Its real bucket  and works with 

```
fs = s3fs.S3FileSystem(anon=None)
fs.ls('xxx')
```

**Comment by hussainsultan** [comment]
best way that i can figure out is try curling the instance metadata service:

```
curl http://169.254.169.254/latest/meta-data/
```
[docs](http://docs.aws.amazon.com/AWSEC2/latest/UserGuide/ec2-instance-metadata.html)

**Comment by martindurant** [comment]
So, if there is data at http://169.254.169.254/latest/meta-data/iam/info , and no explicit key/secret/token were supplied, it's reasonable to assume that we have IAM privileges?

**Comment by hussainsultan** [comment]
its reasonable to assume that we are running on EC2 and *should* add an IAM role for S3 access.

i think the culprit is this :https://github.com/dask/dask/blob/master/dask/bytes/s3.py#L70

**Comment by hussainsultan** [comment]
I tried running it like so:

```python 
fs = s3fs.S3FileSystem(anon=None)
data = dask.dataframe.read_csv('s3://xxx.csv', s3=fs)
```

and got the same error `ClientError`:
```python
ClientError: An error occurred (AccessDenied) when calling the GetSessionToken operation: Cannot call GetSessionToken with session credentials
```

**Comment by hussainsultan** [comment]
for completeness: 

```
curl http://169.254.169.254/latest/meta-data/iam/security-credentials/{my_IAM_role_name}/
{
  "Code" : "Success",
  "LastUpdated" : "2016-05-25T18:17:09Z",
  "Type" : "AWS-HMAC",
  "AccessKeyId" : "xxx",
  "SecretAccessKey" : "xxx",
  "Token" : "xxx",
  "Expiration" : "2016-05-26T00:34:29Z"
}
```

I believe it is still possible that your token will not grant you access to S3 (since it could be for Redshift only etc.)  as it is tied to the IAM role that was attached and only way to know if you have the correct IAM role attached is perhaps through trying and excepting a `AccessDenied` message.

**Comment by martindurant** [comment]
I believe the method that boto3 used to automatically establish credentials must be buried in the s3 client or session objects somewhere - it must be doing some form of access denied check too. 

Previously I had a simple `ls('')` as a check to see whether credentialed access succeeded, but this failed when a user did not have LIST_BUCKETS access, only LIST_OBJECTS.

The test could be to see if generating a token fails, but that requires an extra call to s3 every time, and in the case that some machines have correct roles and others do not, would produce non-obvious errors.

**Comment by hussainsultan** [comment]
boto3 might also use some type of a hierarchical checking of the form:  look for kwargs , if not look for env and all the way to IAM roles and then try.

**Comment by hussainsultan** [comment]
I recommend as much as possible to use `boto3` mechanism for keys rather than using STS service; this may be too simplistic for other use cases where the compute nodes are not running on AWS and need access to S3 buckets.

**Comment by martindurant** [comment]
Seems to be this:
`botocore.utils.InstanceMetadataFetcher().retrieve_iam_role_credentials()`
https://github.com/boto/botocore/blob/develop/botocore/utils.py#L144

We still don't have a way to know if we should distribute (temporary) credentials or not. I see that you suggest the user should have set their environment/config files/IAM roles correctly before starting. That's what we initially had done too. But *if* the user provides the key/secret as overrides, sending these to workers might be fine or might be dangerous.

**Comment by hussainsultan** [comment]
@martindurant In my experience, sending keys can be unsafe and people generally have highly opinionated patterns on how keys  and such things are managed. Unless there is a known usage pattern that is important to users, i will vote for letting people manage their own keys distributions things outside of `dask`. 

Is there a recommended next step that i can take? I do not have the ability to install dask from master at this point so i am hoping there is a way to push a fix to conda.

**Comment by hussainsultan** [comment]
Perhaps, a short term fix relies on a kwarg like `use_metadata_service` passed to read_csv method? Thoughts?

**Comment by martindurant** [comment]
Let me work up a solution for you tomorrow. Are you on a short timeline for this?
Once something is working (perhaps with the keyword you mention or even module-level variables), turning out a conda package should be fast.

**Comment by hussainsultan** [comment]
It's not urgent. This will be super helpful to have. In the meantime, I will move data to hdfs  I am happy to help in anyway as well.

**Comment by hussainsultan** [comment]
@martindurant  Just an FYI- i have started working on a PR for this issue. Thanks!

**Comment by martindurant** [comment]
I believe the PR linked above should solve this for you. Also, we are changing read_csv to be able to pass keyword arguments to the storage backend (hdfs3, s3fs or something else) https://github.com/dask/dask/pull/1184

**Comment by hussainsultan** [comment]
oh you beat me to it! Thanks

**Comment by hussainsultan** [comment]
Wouldnt the issue persist because of https://github.com/dask/dask/blob/master/dask/bytes/s3.py#L70?

**Comment by hussainsultan** [comment]
Let me try this out on ec2 instance and i will report back.

**Comment by hussainsultan** [comment]
@martindurant this works! Thank you. I love how this was solved downstream to `dask`.

**Comment by martindurant** [comment]
Excellent. Any other comments on https://github.com/dask/s3fs/pull/51

**Comment by hussainsultan** [comment]
Looks good to me. Do you know how soon dask/s3fs#51 can be pushed to `conda`?

**Comment by mrocklin** [comment]
@hussainsultan are you able to download from third-party channels or just the default channel?

**Comment by hussainsultan** [comment]
@mrocklin i believe its just default for now but that may change soon as we get internal conda repo.

**Comment by mrocklin** [comment]
Usually default channels get updated within 24 hours of a release to PyPI.  We can trigger a release and expend a bit of social capital to get this done more quickly.  However long-term we probably can't do this very often.  We probably can't treat the default channel as a bleeding-edge repository.  I anticipate that this problem will recur as other flaws/features evolve.

**Comment by hussainsultan** [comment]
That makes sense. I am happy with 24 hours for this. However, i totally get that this is not a best practice at all. I am pushing for better conda support internally and once that happens i think i could do things internally much more easily. Thank you!

**Comment by hussainsultan** [comment]
closing. thank you!

**Comment by hussainsultan** [comment]
@martindurant do you know if this has been pushed to conda default or conda-forge channel?

**Comment by martindurant** [comment]
Yes, I think it's already in 0.0.5, released ~2 weeks ago; and we are also pushing out 0.0.6 right now, it should appear on conda-forge soon.

**Comment by mrocklin** [comment]
I would hope that it would also be released to the `default` channel by now (which is important for people within larger enterprises).  Sadly that appears not to be the case.

@hussainsultan I'm planning to do a full release of most dask related libraries soon.  I'll check that things are properly propagated to default early next week.

**Comment by hussainsultan** [comment]
some reason i cant get `s3fs==0.0.5` from conda forge inside my enterprise setup

**Comment by martindurant** [comment]
Agreed, something is going wrong - installation of 0.0.5 and 0.0.6 seem to work, but the package that appears (by `s3fs.__version__`) in 0.0.4 .

**Comment by martindurant** [comment]
In what way you can't get it? 
(After initial paths confusion at my end) I can confirm that 0.0.5 and 0.0.6 install fine for me from conda forge (py35, osx). Of course, I am not on enterprise.

**Comment by hussainsultan** [comment]
ahh success! it is actually 0.0.5. s3fs.__version__ may not have been updated?

**Comment by hussainsultan** [comment]
@martindurant it was user error, i wasnt pulling it from `conda-forge` channel correctly. it works now. Thank you!
