### ISSUE TITLE
leaking file descriptors

### ISSUE THREAD

**Issue by akcheung** [dask/dask#1411]
I believe either the scheduler or the workers are not closing file descriptors appropriately after calling `scatter`. Sample code:

```
import psutil
print(psutil.Process().num_fds())

from distributed import Executor
executor = Executor() 

import numpy as np
from dask import delayed, compute

for i in range(0,10):
  #data = np.random.randint(0, 1000, size=(145, 174, 145, 288))
  data = np.random.randint(0, 1000, size=(145, 174, 145, 2))
  print(psutil.Process().num_fds())

  remote_slices = executor.scatter([data[..., i] for i in range(data.shape[-1])])
  print(psutil.Process().num_fds())

  jobs = [delayed(len)(slice) for slice in remote_slices]
  print(psutil.Process().num_fds())

  j = compute(*jobs, get=executor.get)
  print(psutil.Process().num_fds())
```

This prints
```
4
751
803
803
805
805
822
822
824
824
831
831
833
833
852
852
854
854
871
871
873
873
875
875
877
877
879
879
881
881
883
883
885
885
887
887
889
889
891
891
893
```

And if you use the commented out line to generate data then the program crashes with `Too many open files` on my machine.

**Comment by mrocklin** [comment]
Here it is running on Python 3.4 on a 4 core machine running Ubuntu 16.04

```python
In [1]: paste
import psutil
print(psutil.Process().num_fds())

from distributed import Executor
executor = Executor() 

import numpy as np
from dask import delayed, compute

for i in range(0,10):
  #data = np.random.randint(0, 1000, size=(145, 174, 145, 288))
  data = np.random.randint(0, 1000, size=(145, 174, 145, 2))
  print(psutil.Process().num_fds())

  remote_slices = executor.scatter([data[..., i] for i in range(data.shape[-1])])
  print(psutil.Process().num_fds())

  jobs = [delayed(len)(slice) for slice in remote_slices]
  print(psutil.Process().num_fds())

  j = compute(*jobs, get=executor.get)
  print(psutil.Process().num_fds())
## -- End pasted text --
9
42
50
50
52
54
54
54
56
56
58
58
58
58
58
58
58
58
58
58
58
58
58
58
58
58
58
58
58
58
58
58
58
58
58
58
58
58
70
70
70
```

Can you say a bit about your hardware and software setup?

**Comment by mrocklin** [comment]
Increasing the last dimension of the numpy array doesn't seem to affect things: 

```python
import psutil
print(psutil.Process().num_fds())

from distributed import Executor
executor = Executor() 

import numpy as np
from dask import delayed, compute

for i in range(0,10):
  #data = np.random.randint(0, 1000, size=(145, 174, 145, 288))
  data = np.random.randint(0, 1000, size=(145, 174, 145, 2))
  print(psutil.Process().num_fds())

  remote_slices = executor.scatter([data[..., i] for i in range(data.shape[-1])])
  print(psutil.Process().num_fds())

  jobs = [delayed(len)(slice) for slice in remote_slices]
  print(psutil.Process().num_fds())

  j = compute(*jobs, get=executor.get)
  print(psutil.Process().num_fds())
```

**Comment by akcheung** [comment]
I ran mine on Python 3.4 on a 120 core server running Ubuntu 14.04 with 1TB of ram (hence I suppose the worker will be using many more threads)

When I increased the data array from (145, 174, 145, 2) to (145, 174, 145, 288) I got:

```
4
764
distributed.utils - ERROR - [Errno 24] Too many open files
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/distributed/utils.py", line 102, in f
  File "/usr/local/lib/python3.4/dist-packages/tornado/gen.py", line 1015, in run
  File "/usr/local/lib/python3.4/dist-packages/tornado/concurrent.py", line 237, in result
  File "<string>", line 3, in raise_exc_info
  File "/usr/local/lib/python3.4/dist-packages/tornado/gen.py", line 1021, in run
  File "/usr/local/lib/python3.4/dist-packages/distributed/executor.py", line 783, in _scatter
  File "/usr/local/lib/python3.4/dist-packages/tornado/gen.py", line 1015, in run
  File "/usr/local/lib/python3.4/dist-packages/tornado/concurrent.py", line 237, in result
  File "<string>", line 3, in raise_exc_info
  File "/usr/local/lib/python3.4/dist-packages/tornado/gen.py", line 1021, in run
  File "/usr/local/lib/python3.4/dist-packages/distributed/core.py", line 438, in send_recv_from_rpc
  File "/usr/local/lib/python3.4/dist-packages/tornado/gen.py", line 1015, in run
  File "/usr/local/lib/python3.4/dist-packages/tornado/concurrent.py", line 237, in result
  File "<string>", line 3, in raise_exc_info
  File "/usr/local/lib/python3.4/dist-packages/tornado/gen.py", line 1024, in run
  File "/usr/local/lib/python3.4/dist-packages/distributed/core.py", line 340, in send_recv
  File "/usr/local/lib/python3.4/dist-packages/six.py", line 685, in reraise
  File "/usr/local/lib/python3.4/dist-packages/distributed/core.py", line 206, in handle_stream
  File "/usr/local/lib/python3.4/dist-packages/tornado/gen.py", line 1015, in run
  File "/usr/local/lib/python3.4/dist-packages/tornado/concurrent.py", line 237, in result
  File "<string>", line 3, in raise_exc_info
  File "/usr/local/lib/python3.4/dist-packages/tornado/gen.py", line 1021, in run
  File "/usr/local/lib/python3.4/dist-packages/distributed/scheduler.py", line 1577, in scatter
  File "/usr/local/lib/python3.4/dist-packages/tornado/gen.py", line 1015, in run
  File "/usr/local/lib/python3.4/dist-packages/tornado/concurrent.py", line 237, in result
  File "<string>", line 3, in raise_exc_info
  File "/usr/local/lib/python3.4/dist-packages/tornado/gen.py", line 1021, in run
  File "/usr/local/lib/python3.4/dist-packages/distributed/client.py", line 229, in scatter_to_workers
  File "/usr/local/lib/python3.4/dist-packages/tornado/gen.py", line 1015, in run
  File "/usr/local/lib/python3.4/dist-packages/tornado/concurrent.py", line 237, in result
  File "<string>", line 3, in raise_exc_info
  File "/usr/local/lib/python3.4/dist-packages/tornado/gen.py", line 1021, in run
  File "/usr/local/lib/python3.4/dist-packages/distributed/utils.py", line 80, in All
  File "/usr/local/lib/python3.4/dist-packages/tornado/gen.py", line 1015, in run
  File "/usr/local/lib/python3.4/dist-packages/tornado/concurrent.py", line 237, in result
  File "<string>", line 3, in raise_exc_info
  File "/usr/local/lib/python3.4/dist-packages/tornado/gen.py", line 1021, in run
  File "/usr/local/lib/python3.4/dist-packages/distributed/core.py", line 437, in send_recv_from_rpc
  File "/usr/local/lib/python3.4/dist-packages/tornado/gen.py", line 1015, in run
  File "/usr/local/lib/python3.4/dist-packages/tornado/concurrent.py", line 237, in result
  File "<string>", line 3, in raise_exc_info
  File "/usr/local/lib/python3.4/dist-packages/tornado/gen.py", line 1021, in run
  File "/usr/local/lib/python3.4/dist-packages/distributed/core.py", line 421, in live_stream
  File "/usr/local/lib/python3.4/dist-packages/tornado/gen.py", line 1015, in run
  File "/usr/local/lib/python3.4/dist-packages/tornado/concurrent.py", line 237, in result
  File "<string>", line 3, in raise_exc_info
  File "/usr/local/lib/python3.4/dist-packages/tornado/gen.py", line 1021, in run
  File "/usr/local/lib/python3.4/dist-packages/distributed/core.py", line 295, in connect
  File "/usr/local/lib/python3.4/dist-packages/tornado/gen.py", line 1015, in run
  File "/usr/local/lib/python3.4/dist-packages/tornado/concurrent.py", line 237, in result
  File "<string>", line 3, in raise_exc_info
  File "/usr/local/lib/python3.4/dist-packages/tornado/gen.py", line 1024, in run
  File "/usr/local/lib/python3.4/dist-packages/tornado/tcpclient.py", line 168, in connect
  File "/usr/local/lib/python3.4/dist-packages/tornado/tcpclient.py", line 81, in start
  File "/usr/local/lib/python3.4/dist-packages/tornado/tcpclient.py", line 96, in try_connect
  File "/usr/local/lib/python3.4/dist-packages/tornado/tcpclient.py", line 180, in _create_stream
  File "/usr/lib/python3.4/socket.py", line 126, in __init__
OSError: [Errno 24] Too many open files
```

**Comment by mrocklin** [comment]
OK the 120 core server makes things a lot more clear here.  It looks like each connection from scheduler to worker takes on the order of 10 connections.  If you have 120 logical cores then it will try to open 1200 files, which, with default linux settings, will blow past the default limit of 1024 open files.

We could shrink this down a bit, but not by more than a factor of two in the near future.  There is a decent amount of asynchronous communication back and forth between everyone.

I think I recall your e-mail saying that you had set the open file limit.  Is it possible that this process wasn't completed somehow?  I usually do this by appending the following lines to `/etc/security/limits.conf`

    my_username soft nofile 102400
    my_username hard nofile 102400

I then make sure to restart the terminal from which I launch things to make sure it gets these new limits.

http://www.cyberciti.biz/faq/linux-increase-the-maximum-number-of-open-files/

**Comment by akcheung** [comment]
Indeed setting the file limit helped. But I am still observing an increasing number of file handles:
```
4
783
8480
8502
9042
11901
17966
18049
18228
20275
26722
26746
26905
27511
28157
28159
28159
28159
28260
28260
```
Is there a reason for this?

Two other observations: 

Our actual production setting uses 16 ec2 m3.2xlarge machines, and running on that cluster still returns `Too many opened files` error even after setting `ulimit -n` to be 1000000 on all machines.

And when I ran the test code on one of the m3.2xlarge machines locally with `data = np.random.randint(0, 1000, size=(145, 174, 145, 288))` I got:

```
4
127
Traceback (most recent call last):
  File "t.py", line 17, in <module>
    remote_slices = executor.scatter([data[..., i] for i in range(data.shape[-1])])
  File "/usr/local/lib/python3.4/dist-packages/distributed/executor.py", line 885, in scatter
    broadcast=broadcast)
  File "/usr/local/lib/python3.4/dist-packages/distributed/utils.py", line 116, in sync
    six.reraise(type(error[0]), error[0], traceback[0])
  File "/usr/lib/python3/dist-packages/six.py", line 536, in reraise
    raise value
  File "/usr/local/lib/python3.4/dist-packages/distributed/utils.py", line 102, in f
    result[0] = yield gen.maybe_future(func(*args, **kwargs))
  File "/usr/local/lib/python3.4/dist-packages/tornado/gen.py", line 1015, in run
    value = future.result()
  File "/usr/local/lib/python3.4/dist-packages/tornado/concurrent.py", line 237, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 3, in raise_exc_info
  File "/usr/local/lib/python3.4/dist-packages/tornado/gen.py", line 1021, in run
    yielded = self.gen.throw(*exc_info)
  File "/usr/local/lib/python3.4/dist-packages/distributed/executor.py", line 783, in _scatter
    client=self.id, broadcast=broadcast)
  File "/usr/local/lib/python3.4/dist-packages/tornado/gen.py", line 1015, in run
    value = future.result()
  File "/usr/local/lib/python3.4/dist-packages/tornado/concurrent.py", line 237, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 3, in raise_exc_info
  File "/usr/local/lib/python3.4/dist-packages/tornado/gen.py", line 1021, in run
    yielded = self.gen.throw(*exc_info)
  File "/usr/local/lib/python3.4/dist-packages/distributed/core.py", line 438, in send_recv_from_rpc
    result = yield send_recv(stream=stream, op=key, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/tornado/gen.py", line 1015, in run
    value = future.result()
  File "/usr/local/lib/python3.4/dist-packages/tornado/concurrent.py", line 237, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 3, in raise_exc_info
  File "/usr/local/lib/python3.4/dist-packages/tornado/gen.py", line 1021, in run
    yielded = self.gen.throw(*exc_info)
  File "/usr/local/lib/python3.4/dist-packages/distributed/core.py", line 335, in send_recv
    yield write(stream, msg)
  File "/usr/local/lib/python3.4/dist-packages/tornado/gen.py", line 1015, in run
    value = future.result()
  File "/usr/local/lib/python3.4/dist-packages/tornado/concurrent.py", line 237, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 3, in raise_exc_info
  File "/usr/local/lib/python3.4/dist-packages/tornado/gen.py", line 285, in wrapper
    yielded = next(result)
  File "/usr/local/lib/python3.4/dist-packages/distributed/core.py", line 269, in write
    frames = protocol.dumps(msg)
  File "/usr/local/lib/python3.4/dist-packages/distributed/protocol.py", line 81, in dumps
    frames = dumps_msgpack(small)
  File "/usr/local/lib/python3.4/dist-packages/distributed/protocol.py", line 153, in dumps_msgpack
    payload = msgpack.dumps(msg, use_bin_type=True)
  File "/usr/local/lib/python3.4/dist-packages/msgpack/__init__.py", line 47, in packb
    return Packer(**kwargs).pack(o)
SystemError: error return without exception set
```

Not sure if the two errors are related.

**Comment by mrocklin** [comment]
The other error that you've reported in #1412 is, I think, unrelated.

**Comment by akcheung** [comment]
Any suggestions to work around the too many files opened error? (which I guess was a work around for [#1412](https://github.com/dask/dask/issues/1412))

**Comment by mrocklin** [comment]
20000 open file handles for 120 cores definitely sounds like far too many.  Here is my experience with a 100 process local cluster on my laptop:

```python

In [1]: from distributed import Executor, LocalCluster

In [2]: c = LocalCluster(100)

In [3]: c
Out[3]: LocalCluster("127.0.0.1:8786", workers=100, ncores=400)

In [4]: executor = Executor(c)

In [5]: exec
exec      executor  

In [5]: executor
Out[5]: <Executor: scheduler="127.0.0.1:8786" processes=100 cores=400>

In [6]: import psutil

In [7]: print(psutil.Process().num_fds())
621

In [8]: import numpy as np

In [9]: from dask import delayed, compute

In [10]: for i in range(0,10):
    data = np.random.randint(0, 1000, size=(174, 145, 200))
    print(psutil.Process().num_fds())
    remote_slices = executor.scatter([data[..., i] for i in range(data.shape[-1])])
    print(psutil.Process().num_fds())
    jobs = [delayed(len)(slice) for slice in remote_slices]
    print(psutil.Process().num_fds())
    j = compute(*jobs, get=executor.get)
    print(psutil.Process().num_fds())
   ....:     
620
620
620
670
670
720
720
770
770
916
916
916
916
916
916
916
916
916
916
916
916
916
916
916
916
916
916
916
916
916
916
916
916
916
916
916
916
916
916
916
```

What operating system are you running?  What hardware do you have that has 120 cores on one machine?

> Any suggestions to work around the too many files opened error? 

I'm inclined to figure out what's going on and fix it.  

> which I guess was a work around for #1412 

I'm not sure I understand this comment.  Can you clarify?

**Comment by mrocklin** [comment]
Also how did you install things?  What version of Tornado are you using?

**Comment by akcheung** [comment]
> What operating system are you running? What hardware do you have that has 120 cores on one machine?

This was a high-end server running ubuntu 14.04 that does have 120 cores. That aside, even when running the code I pasted at the top on an aws machine with 8 cores the # of files grew to 643 when finished (the # of files didn't stay constant as in your case running on the laptop). Is that behavior intended? I imagine it will run out of handles eventually regardless of the machine settings.

> which I guess was a work around for #1412

As you recall using `scatter` was your suggested workaround for the out of memory error I raised earlier. Seems like I am hitting the file handle issue when using that workaround.

> Also how did you install things? What version of Tornado are you using?

Everything was installed using `pip3`:
```
pip3 show tornado dask distributed
---
Name: tornado
Version: 4.4
Location: /usr/local/lib/python3.4/dist-packages
Requires: backports-abc
---
Name: dask
Version: 0.10.1
Location: /usr/local/lib/python3.4/dist-packages
Requires:
ubuntu@ip-172-31-4-204:~$ pip3 show tornado dask distributed
---
Name: distributed
Version: 1.11.2
Location: /usr/local/lib/python3.4/dist-packages
Requires: cloudpickle, dask, locket, toolz, msgpack-python, psutil, boto3, six, tblib, click, s3fs, tornado
```

**Comment by mrocklin** [comment]
> This was a high-end server running ubuntu 14.04 that does have 120 cores. That aside, even when running the code I pasted at the top on an aws machine with 8 cores the # of files grew to 643 when finished (the # of files didn't stay constant as in your case running on the laptop). Is that behavior intended? I imagine it will run out of handles eventually regardless of the machine settings.

We definitely expect a near constant number of file descriptors.  The system is decently intelligent about pooling connections and only opening new streams if more concurrent connections are required.  This is pretty rare.  Scattering shouldn't have a significant effect.  It doesn't consume a significant number of connections.

I've tried installing a similar software environment to yours tools and still get my normal results.

```
(fds) mrocklin@notebook:~$ pip freeze
backports-abc==0.4
boto3==1.3.1
botocore==1.4.39
click==6.6
cloudpickle==0.2.1
dask==0.10.1
decorator==4.0.10
distributed==1.11.2
docutils==0.12
ipython==5.0.0
ipython-genutils==0.1.0
jmespath==0.9.0
locket==0.2.0
msgpack-python==0.4.7
numpy==1.11.1
pexpect==4.2.0
pickleshare==0.7.3
prompt-toolkit==1.0.3
psutil==4.3.0
ptyprocess==0.5.1
Pygments==2.1.3
python-dateutil==2.5.3
s3fs==0.0.6
simplegeneric==0.8.1
six==1.10.0
tblib==1.3.0
toolz==0.8.0
tornado==4.4.1
traitlets==4.2.2
wcwidth==0.1.7
```

I can try some EC2 hardware tomorrow.  Anything special I should consider?

**Comment by mrocklin** [comment]
OK, I'm running on some hardware generously provided by @akcheung 

OK, so I am seeing an interesting correlation that, as the size of the data increases so too does the number of file descriptors.  This appears to be sub-linear, but is fairly interesting.  Perhaps there is some OS-level caching going on that keeps old sockets alive?

Regardless, I'm not seeing a leaking effect, the number remains constant.

```
dasktest@ip-172-31-4-204:~$ python3 mrocklin-test.py 
4
<Executor: scheduler="127.0.0.1:9999" processes=8 cores=8>
66
217
217
217
225
268
268
268
268
268
268
268
268
268
268
268
268
268
268
268
268
```

When I tone the size of the data down significantly it seems to level out at 70 open files, which is at our same 10x nworkers from before. 

Something that may have been screwing with numbers before is that there are a lot of dask-worker processes somewhere that are actively trying to connect to the 8786 port.  So when we start up a simple `Executor()` with a local cluster, he immediately gets swarmed by twenty other dask-workers around.  I don't have permissions to kill these so I moved to a new port.

I've tried this with the system installation and a user-side miniconda installation and they both perform about the same.

**Comment by akcheung** [comment]
Thanks @mrocklin . We just shutdown the other dask-workers so 8786 port should work now. Any idea what is going on with the full (145, 174, 145, 288) dataset? Right now it just crashes.

**Comment by mrocklin** [comment]
At the moment, no, I don't know what's going on.  There is a clear dependence on the amount of data sent with the number of file descriptors.  Nothing in the dask.distributed codebase handles anything like this though.  We've just opened up a small handful of Tornado IOStreams.  I'll look a bit upstream and see if anything is going on with Tornado or any of the compression libraries.

**Comment by mrocklin** [comment]
I'm probably not going to get anything else done today though.  if you'd like to shut down your EC2 machine now would be a good time.

**Comment by akcheung** [comment]
Great. Thanks @mrocklin for looking into this.

**Comment by mrocklin** [comment]
I believe that this was caused by heartbeats piling up due to heavy network traffic.  The system was clever enough to notice that existing channels were full and so kept opening up new ones, causing the issue here.

I believe that this is fixed in https://github.com/dask/distributed/pull/388

**Comment by akcheung** [comment]
Just pulled the latest from the repo but I'm still getting a `SystemError` in `Packer` when running the full (145, 174, 145, 288) dataset test case. Did I miss a step somewhere?

```
$ pip3 show distributed
---
Name: distributed
Version: 1.11.3
Location: /usr/local/lib/python3.4/dist-packages
```

Test output:
```
4
63
distributed.utils - ERROR - error return without exception set
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/distributed/utils.py", line 102, in f
    result[0] = yield gen.maybe_future(func(*args, **kwargs))
  File "/usr/local/lib/python3.4/dist-packages/tornado/gen.py", line 1015, in run
    value = future.result()
  File "/usr/local/lib/python3.4/dist-packages/tornado/concurrent.py", line 237, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 3, in raise_exc_info
  File "/usr/local/lib/python3.4/dist-packages/tornado/gen.py", line 1021, in run
    yielded = self.gen.throw(*exc_info)
  File "/usr/local/lib/python3.4/dist-packages/distributed/executor.py", line 787, in _scatter
    client=self.id, broadcast=broadcast)
  File "/usr/local/lib/python3.4/dist-packages/tornado/gen.py", line 1015, in run
    value = future.result()
  File "/usr/local/lib/python3.4/dist-packages/tornado/concurrent.py", line 237, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 3, in raise_exc_info
  File "/usr/local/lib/python3.4/dist-packages/tornado/gen.py", line 1021, in run
    yielded = self.gen.throw(*exc_info)
  File "/usr/local/lib/python3.4/dist-packages/distributed/core.py", line 445, in send_recv_from_rpc
    result = yield send_recv(stream=stream, op=key, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/tornado/gen.py", line 1015, in run
    value = future.result()
  File "/usr/local/lib/python3.4/dist-packages/tornado/concurrent.py", line 237, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 3, in raise_exc_info
  File "/usr/local/lib/python3.4/dist-packages/tornado/gen.py", line 1021, in run
    yielded = self.gen.throw(*exc_info)
  File "/usr/local/lib/python3.4/dist-packages/distributed/core.py", line 339, in send_recv
    yield write(stream, msg)
  File "/usr/local/lib/python3.4/dist-packages/tornado/gen.py", line 1015, in run
    value = future.result()
  File "/usr/local/lib/python3.4/dist-packages/tornado/concurrent.py", line 237, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 3, in raise_exc_info
  File "/usr/local/lib/python3.4/dist-packages/tornado/gen.py", line 285, in wrapper
    yielded = next(result)
  File "/usr/local/lib/python3.4/dist-packages/distributed/core.py", line 273, in write
    frames = protocol.dumps(msg)
  File "/usr/local/lib/python3.4/dist-packages/distributed/protocol.py", line 81, in dumps
    frames = dumps_msgpack(small)
  File "/usr/local/lib/python3.4/dist-packages/distributed/protocol.py", line 155, in dumps_msgpack
    payload = msgpack.dumps(msg, use_bin_type=True)
  File "/usr/local/lib/python3.4/dist-packages/msgpack/__init__.py", line 47, in packb
    return Packer(**kwargs).pack(o)
SystemError: error return without exception set
```

**Comment by mrocklin** [comment]
I haven't resolved the msgpack issue https://github.com/dask/dask/issues/1412.  

I think that I have resolved the file descriptor issue.  

Does your computation still use significantly more than 10x the number of workers fail when using scatter?

**Comment by akcheung** [comment]
For the small dataset the number of files stayed constant after a few iterations. Thanks for looking into that. For the large dataset I wasn't able to tell as it crashed after 2 iterations (see above).

**Comment by mrocklin** [comment]
I wrote the following before looking more deeply at your traceback.  It's still correct so I'm going to send it, however I'm not confident that it is the source of your problem.

The error above means that you have large datasets within the delayed values that you submit up to the scheduler.  This would happen if you did the following:

```python
x = np.random.random(size=large)
v = delayed(f)(x)
x = e.persist(x)
```

It should not happen if you do the following:

```python
x = np.random.random(size=large)
[x] = e.scatter([x])
v = delayed(f)(x)
x = e.persist(x)
```

**Comment by mrocklin** [comment]
It looks like this is actually happening within scatter, which is odd.  I'll take a look when I have time (maybe later today if other things go well)

**Comment by akcheung** [comment]
Here's the full trace:
```
Traceback (most recent call last):
  File "test.py", line 17, in <module>
    remote_slices = executor.scatter([data[..., i] for i in range(data.shape[-1])])
  File "/usr/local/lib/python3.4/dist-packages/distributed/executor.py", line 889, in scatter
    broadcast=broadcast)
  File "/usr/local/lib/python3.4/dist-packages/distributed/utils.py", line 116, in sync
    six.reraise(type(error[0]), error[0], traceback[0])
  File "/usr/local/lib/python3.4/dist-packages/six.py", line 686, in reraise
    raise value
  File "/usr/local/lib/python3.4/dist-packages/distributed/utils.py", line 102, in f
    result[0] = yield gen.maybe_future(func(*args, **kwargs))
  File "/usr/local/lib/python3.4/dist-packages/tornado/gen.py", line 1015, in run
    value = future.result()
  File "/usr/local/lib/python3.4/dist-packages/tornado/concurrent.py", line 237, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 3, in raise_exc_info
  File "/usr/local/lib/python3.4/dist-packages/tornado/gen.py", line 1021, in run
    yielded = self.gen.throw(*exc_info)
  File "/usr/local/lib/python3.4/dist-packages/distributed/executor.py", line 787, in _scatter
    client=self.id, broadcast=broadcast)
  File "/usr/local/lib/python3.4/dist-packages/tornado/gen.py", line 1015, in run
    value = future.result()
  File "/usr/local/lib/python3.4/dist-packages/tornado/concurrent.py", line 237, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 3, in raise_exc_info
  File "/usr/local/lib/python3.4/dist-packages/tornado/gen.py", line 1021, in run
    yielded = self.gen.throw(*exc_info)
  File "/usr/local/lib/python3.4/dist-packages/distributed/core.py", line 438, in send_recv_from_rpc
    result = yield send_recv(stream=stream, op=key, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/tornado/gen.py", line 1015, in run
    value = future.result()
  File "/usr/local/lib/python3.4/dist-packages/tornado/concurrent.py", line 237, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 3, in raise_exc_info
  File "/usr/local/lib/python3.4/dist-packages/tornado/gen.py", line 1021, in run
    yielded = self.gen.throw(*exc_info)
  File "/usr/local/lib/python3.4/dist-packages/distributed/core.py", line 335, in send_recv
    yield write(stream, msg)
  File "/usr/local/lib/python3.4/dist-packages/tornado/gen.py", line 1015, in run
    value = future.result()
  File "/usr/local/lib/python3.4/dist-packages/tornado/concurrent.py", line 237, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 3, in raise_exc_info
  File "/usr/local/lib/python3.4/dist-packages/tornado/gen.py", line 285, in wrapper
    yielded = next(result)
  File "/usr/local/lib/python3.4/dist-packages/distributed/core.py", line 269, in write
    frames = protocol.dumps(msg)
  File "/usr/local/lib/python3.4/dist-packages/distributed/protocol.py", line 81, in dumps
    frames = dumps_msgpack(small)
  File "/usr/local/lib/python3.4/dist-packages/distributed/protocol.py", line 155, in dumps_msgpack
    payload = msgpack.dumps(msg, use_bin_type=True)
  File "/usr/local/lib/python3.4/dist-packages/msgpack/__init__.py", line 47, in packb
    return Packer(**kwargs).pack(o)
SystemError: error return without exception set
```

**Comment by mrocklin** [comment]
I think I've identified the issue.  It might be a day or two before it gets fixed.  We're going to use it as a training issue.  In the mean time you should be able to get by by sending data up in smaller batches.  This is somewhat inefficient but will get you started

    futures = list(e.scatter((data[..., i] for i in range(data.shape[-1])))) 

Notice that we're passing an iterator, not a list, to scatter.  This will pass data up one at a time.

**Comment by akcheung** [comment]
Thanks. FYI I'm still getting the same error after switching to iterators.

**Comment by mrocklin** [comment]
Also @akcheung, you're probably already aware of this, but just in case, it's rare to use scatter on large datasets.  It's far more common to have workers load data themselves.  The reason why we've never run into this issue before is because using scatter in this way is something of an anti-pattern.

It's far more common to, say, create slices on the workers

```python
slices = [delayed(np.random.random)((145, 174, 145)) for i in range(288)]
slices = e.persist(*slices)
```

Or, if what you actually want is a random nd-array use dask.array to construct it for you.

```python
import dask.array as da
x = da.random.random((145, 174, 145, 288), chunks=(145, 174, 145, 1))
x = e.persist(x)
```

**Comment by akcheung** [comment]
Our code has to first download 2GB worth of data and then compute on it. We can't split the download across workers but can distribute it afterwards to workers. Which code do you think will be more efficient?
```
slices = partition(download())
slices = e.scatter(slices)
jobs = e.map(runOnSlice, slices)
e.compute(jobs)
```
or
```
slices = partition(download())
slices = e.scatter(slices)
ds = da.concatenate(futures_to_dask_arrays(slices))
f = delayed(runOnDaskArray)(ds)
e.compute(f)
```

**Comment by mrocklin** [comment]
Not being able to split data ahead of time is unfortunate.  Are there perhaps many 2GB-sized datasets that you need to manage?  Is there any reason to call `download` on the workers themselves?

**Comment by mrocklin** [comment]
You might also want to try out https://github.com/dask/distributed/pull/397

**Comment by akcheung** [comment]
Yes we do have many 2GB datasets to process, but each one can be processed independently so I don't see the need to concatenate them together into a single dask array. Our current strategy is to ask each worker to simultaneously download one or more of the datasets, and then split it across other workers to be processed in parallel. Unless you think it is better to download each dataset on the master sequentially, and then split each one across the workers?

**Comment by mrocklin** [comment]
I agree that it's probably much nicer to download on the workers and split from there.  It's worth noting that large data transfer between workers is a much more commonly used code path, and so is unlikely to suffer from the sorts of issues you were seeing in scatter.

**Comment by akcheung** [comment]
Can you suggest how to scatter data from the workers w/o collecting it on the master? Tried this code but didn't work:

```
def download():
  return np.random.random(10)

e = Executor()
dFuture = e.submit(download)
e.scatter(futures_to_dask_arrays([dF]))
```

Got `TypeError: Cannot serialize socket object`

**Comment by mrocklin** [comment]
This should work:

```python
def download():
    return np.random.random((10, 10, 10))

x = delayed(download)()
slices = [x[:, :, i] for i in range(10)]

slices = e.persist(*slices)
e.rebalance(slices)
```

However given your recent questions I suspect that you would be best served by taking a step back and asking more generally what you're trying to do.  There are many possible approaches to using Dask.
