### ISSUE TITLE
Dask doesn't play well with interrupts

### ISSUE THREAD

**Issue by alanhdu** [dask/dask#1439]
This is on `Python 3.5.2`, `dask 0.10.1`, and `jupyter-notebook 4.2.1`, all installed via conda on a 64-bit Ubuntu machine.

If you run the following piece of code:
```Python
import json

from dask.diagnostics import ProgressBar
import dask.bag as db

j = json.dumps({"a": 1, "b": 1})

for i in range(8):
    data = [j for _ in range(10 ** i)]
    bag = db.from_sequence(data, npartitions=4).map(json.loads)
    with ProgressBar():
        db.zip(bag.pluck("a"), bag.pluck('b')).count().compute()
```

And try to do a keyboard interrupt in the middle, sometimes dask will flip out and just refuse to exit (no matter how many `CTRL-C`s and `CTRL-D`s you press. See https://asciinema.org/a/2yqxbhn1patwenwy024m2316l for a video.

This is especially annoying on a Jupyter notebook. Sometimes, dask will mysteriously keep printing out the progress bar from the last session, even after restarting the kernel (!).

_EDIT_: When this happens, dask will also leave around `python` processes still running. See https://asciinema.org/a/8x1liiyuiw7910mugj9tscher for an example (particularly the extra `python` process at the end).

**Comment by alanhdu** [comment]
Notably, I can only reproduce this in the python repl (and ipython). When I run it as a script (`python test.py`), 3 `KeyboardInterrupt` are enough to exit cleanly without leaving traces of itself anywhere (see https://asciinema.org/a/eitz5acubx6ot7a9cmm1sdz2l)

**Comment by alanhdu** [comment]
...contrary to my previous assumption, this doesn't have anything to do with the progressbar. I just thought it did because the phantom progressbar on a jupyter notebook was how I found out about it.

Everything above can be replicated without the `with ProgressBar():` line.

Sorry for the noise.

**Comment by rolando** [comment]
I noticed that behavior when using ``dask`` in a jupyter notebook: the progressbar running in background after a stop and also orphan processes even after killing all kernels.

FWIW, I used `ProgressBar().register()` at the beginning of the notebook.

**Comment by mrocklin** [comment]
I've so far been unable to reproduce this without a progressbar.

I have been able to reproduce this with the synchronous single-threaded scheduler

**Comment by mrocklin** [comment]
Possibly resolved in #1444

**Comment by alanhdu** [comment]
Confirmed that it was resolved. Thanks!

**Comment by mrocklin** [comment]
Thanks for confirming @alanhdu and for raising in the first place.

**Comment by syagev** [comment]
Something like this still occurs for me with the distributed scheduler running on a `LocalCluster`. When I work in a jupyter notebook, and the notebook is executing a blocking `.compute()` method, and then hitting CTRL+C - the blocking method indeed returns, but all the worker processes are killed (not very gracefully). The end result is that there are zombie python processes and the scheduler reports 0 workers.

So far I haven't found a good way to recover from this without restarting the jupyter kernel, because issuing `Client.restart()` doesn't restart the workers, and trying to execute `Client(LocalCluster())` again gives `port 8787 is already in use`.

If anyone has a good tip on how to workaround that could really help.

**Comment by Holmgren825** [comment]
Chiming in here. I've noticed that if I mistakingly press I, I in a jupyter lab session, without any computations running - maybe moving around editing cells, all workers of a LocalCluster will die/disappear. Usually, I can solve this by `client.shutdown()` followed by a new `client = Client()`, but seems a bit strange to me.
