### ISSUE TITLE
Diagnostics are not compatible with new versions of Bokeh

### ISSUE THREAD

**Issue by ek-nath** [dask/dask#2770]
<pre class="prettyprint lang-py"><code>import pandas as pd
import numpy as np
from dask.diagnostics import Profiler, ResourceProfiler, visualize
from dask import delayed, compute
@delayed
def return_df():
    return pd.DataFrame(np.random.randn(50, 4), columns=list('ABCD'))
df = return_df()
with Profiler() as prof, ResourceProfiler(dt=0.1) as rprof:
    _ = compute(df)
visualize([prof, rprof])
</code></pre>

<img width="185" alt="badbokeh" src="https://user-images.githubusercontent.com/1240693/31522436-a3bf0740-af62-11e7-9768-826b06e111f4.PNG">

This is with bokeh versions: `0.12.7` and `0.12.6`
dask version: `0.15.2`

But when I downgrade bokeh to `0.12.3` (which I guessed by searching `bokeh` in the dask repository :)), the diagnostic visualizations are working fine.

**Comment by mrocklin** [comment]
Have you tried more recent Bokeh versions?  Does this error still persist?

**Comment by jcrist** [comment]
This isn't a general incompatibility, it was only a bug with handling ranges of span == 0. This would occur when the code being profiled runs so quickly (your example above) that only a single point is recorded by the resource profiler.

I've fixed this in #2778.

```
In [1]: import bokeh

In [2]: bokeh.__version__
Out[2]: '0.12.7'

In [3]: import pandas as pd
   ...: import numpy as np
   ...: from dask.diagnostics import Profiler, ResourceProfiler, visualize
   ...: from dask import delayed, compute
   ...: @delayed
   ...: def return_df():
   ...:     return pd.DataFrame(np.random.randn(50, 4), columns=list('ABCD'))
   ...: df = return_df()
   ...: with Profiler() as prof, ResourceProfiler(dt=0.1) as rprof:
   ...:     _ = compute(df)
   ...:

In [4]: len(rprof.results)  # only a single result
Out[4]: 1

In [5]: visualize([prof, rprof])
Out[5]: Column(id='32b02228-b311-4e10-9b70-53b0882a3052', ...)
```

Plot:
<img width="823" alt="screen shot 2017-10-13 at 2 51 01 pm" src="https://user-images.githubusercontent.com/2783717/31563755-014687a8-b026-11e7-8acd-29a43403e341.png">

**Comment by ek-nath** [comment]
@jcrist I am still getting the same error with bokeh version `0.12.9`. Should I check some other library's version? I am not sure what's going wrong here.
![image](https://user-images.githubusercontent.com/1240693/31578546-4a77aab2-b0d8-11e7-8c0c-fa71a3e0a502.png)

<pre><code>
Python 3.6.2 |Anaconda custom (64-bit)| (default, Sep 19 2017, 08:03:39) [MSC v.1900 64 bit (AMD64)]
Type 'copyright', 'credits' or 'license' for more information
IPython 6.1.0 -- An enhanced Interactive Python. Type '?' for help.

In [1]: import bokeh
   ...: import pandas as pd
   ...: import numpy as np
   ...:

In [2]: bokeh.__version__
   ...:
Out[2]: '0.12.9'

In [3]: from dask.diagnostics import Profiler, ResourceProfiler, visualize
   ...: from dask import delayed, compute
   ...:

In [4]: @delayed
   ...: def return_df():
   ...:     return pd.DataFrame(np.random.randn(50, 4), columns=list('ABCD'))
   ...: df = return_df()
   ...: with Profiler() as prof, ResourceProfiler(dt=0.1) as rprof:
   ...:     _ = compute(df)
   ...:

In [5]: len(rprof.results)  # only a single result
Out[5]: 1

In [6]: visualize([prof, rprof])
C:\Users\user\Anaconda3\lib\site-packages\bokeh\util\deprecation.py:34: BokehDeprecationWarning: ResizeTool is removed in Bokeh 0.12.7, adding it is a no-op. In the future, accessing ResizeTool will be an error
  warn(message)
C:\Users\user\Anaconda3\lib\site-packages\bokeh\util\deprecation.py:34: BokehDeprecationWarning: ResizeTool is removed in Bokeh 0.12.7, adding it is a no-op. In the future, accessing ResizeTool will be an error
  warn(message)
Out[6]: Column(id='04969e8e-f1fa-41aa-8a90-ddb9c576748e', ...)
In [12]: dask.__version__
Out[12]: '0.15.2'

In [13]: np.__version__
Out[13]: '1.13.1'

In [14]: pd.__version__
Out[14]: '0.20.3'
</code></pre>

**Comment by jcrist** [comment]
Are you using the patch from [the PR](https://github.com/dask/dask/pull/2778)? The fix was in dask, not in bokeh. I have confirmed that it works with at least bokeh 0.12.6 - 0.12.9.

If you want to try out the patch, you can install with `pip`:

```
pip install -U git+https://github.com/jcrist/dask.git@resourceplot-fix
```

If you wait until tomorrow, I'll merge the PR, then you can install with:

```
pip install -U git+https://github.com/dask/dask.git
```

**Comment by jcrist** [comment]
This is now fixed in the master branch:

`pip install -U git+https://github.com/dask/dask.git`

**Comment by ek-nath** [comment]
Confirming that this issue is fixed. Thanks @jcrist
