### ISSUE TITLE
CI failures against dev dependencies

### ISSUE THREAD

**Issue by jakirkham** [dask/dask#3221]
Seeing some failures on `master` with the development dependencies as noted in [this log]( https://api.travis-ci.org/v3/job/346782353/log.txt ). Snippet of the failures listed in the details below. Seems caused by field access primarily.

<details>

```python
=================================== FAILURES ===================================
_________________________ test_field_access_with_shape _________________________
[gw2] linux -- Python 3.6.4 /home/travis/miniconda/envs/test-environment/bin/python

    def test_field_access_with_shape():
        dtype = [('col1', ('f4', (3, 2))), ('col2', ('f4', 3))]
        data = np.ones((100, 50), dtype=dtype)
        x = da.from_array(data, 10)
        assert_eq(x['col1'], data['col1'])
>       assert_eq(x[['col1']], data[['col1']])

dask/array/tests/test_array_core.py:804: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

a = array([[([[1., 1.], [1., 1.], [1., 1.]],),
        ([[1., 1.], [1., 1.], [1., 1.]],),
        ([[1., 1.], [1., 1.], [1....], [1., 1.], [1., 1.]],)]],
      dtype={'names':['col1'], 'formats':[('<f4', (3, 2))], 'offsets':[0], 'itemsize':36})
b = array([[([[1., 1.], [1., 1.], [1., 1.]],),
        ([[1., 1.], [1., 1.], [1., 1.]],),
        ([[1., 1.], [1., 1.], [1....], [1., 1.], [1., 1.]],)]],
      dtype={'names':['col1'], 'formats':[('<f4', (3, 2))], 'offsets':[0], 'itemsize':36})
check_shape = True, kwargs = {}
a_original = dask.array<getitem, shape=(100, 50), dtype=[('col1', '<f4', (3, 2))], chunksize=(10, 10)>
b_original = array([[([[1., 1.], [1., 1.], [1., 1.]],),
        ([[1., 1.], [1., 1.], [1., 1.]],),
        ([[1., 1.], [1., 1.], [1....], [1., 1.], [1., 1.]],)]],
      dtype={'names':['col1'], 'formats':[('<f4', (3, 2))], 'offsets':[0], 'itemsize':36})
adt = dtype([('col1', '<f4', (3, 2))])

    def assert_eq(a, b, check_shape=True, **kwargs):
        a_original = a
        b_original = b
        if isinstance(a, Array):
            assert a.dtype is not None
            adt = a.dtype
            _check_dsk(a.dask)
            a = a.compute(get=get_sync)
            if hasattr(a, 'todense'):
                a = a.todense()
            if not hasattr(a, 'dtype'):
                a = np.array(a, dtype='O')
            if _not_empty(a):
>               assert a.dtype == a_original.dtype
E               AssertionError

dask/array/utils.py:86: AssertionError
______________________________ test_field_access _______________________________
[gw0] linux -- Python 3.6.4 /home/travis/miniconda/envs/test-environment/bin/python

    def test_field_access():
        x = np.array([(1, 1.0), (2, 2.0)], dtype=[('a', 'i4'), ('b', 'f4')])
        y = from_array(x, chunks=(1,))
        assert_eq(y['a'], x['a'])
>       assert_eq(y[['b', 'a']], x[['b', 'a']])

dask/array/tests/test_array_core.py:795: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

a = array([(1., 1), (2., 2)],
      dtype={'names':['b','a'], 'formats':['<f4','<i4'], 'offsets':[4,0], 'itemsize':8})
b = array([(1., 1), (2., 2)],
      dtype={'names':['b','a'], 'formats':['<f4','<i4'], 'offsets':[4,0], 'itemsize':8})
check_shape = True, kwargs = {}
a_original = dask.array<getitem, shape=(2,), dtype=[('b', '<f4'), ('a', '<i4')], chunksize=(1,)>
b_original = array([(1., 1), (2., 2)],
      dtype={'names':['b','a'], 'formats':['<f4','<i4'], 'offsets':[4,0], 'itemsize':8})
adt = dtype([('b', '<f4'), ('a', '<i4')])

    def assert_eq(a, b, check_shape=True, **kwargs):
        a_original = a
        b_original = b
        if isinstance(a, Array):
            assert a.dtype is not None
            adt = a.dtype
            _check_dsk(a.dask)
            a = a.compute(get=get_sync)
            if hasattr(a, 'todense'):
                a = a.todense()
            if not hasattr(a, 'dtype'):
                a = np.array(a, dtype='O')
            if _not_empty(a):
>               assert a.dtype == a_original.dtype
E               AssertionError

dask/array/utils.py:86: AssertionError
_______________________ test_slice_dtype[dtype0-index0] ________________________
[gw2] linux -- Python 3.6.4 /home/travis/miniconda/envs/test-environment/bin/python

dtype = dtype([('A', '<f4', (3, 2)), ('B', '<f4', (3,)), ('C', '<f8', (3,))])
index = ['A']

    def test_slice_dtype(dtype, index):
        result = _make_sliced_dtype(dtype, index)
        expected = np.ones((5, len(dtype)), dtype=dtype)[index].dtype
>       assert result == expected
E       AssertionError: assert dtype([('A', '<f4', (3, 2))]) == dtype({'names':['A'], 'formats':[('<f4', (3, 2))], 'offsets':[0], 'itemsize':60})

dask/array/tests/test_numpy_compat.py:39: AssertionError
_______________________ test_slice_dtype[dtype1-index0] ________________________
[gw2] linux -- Python 3.6.4 /home/travis/miniconda/envs/test-environment/bin/python

dtype = dtype([('A', '<i4', (3, 2)), ('B', '<f4', (3,)), ('C', 'S4', (3,))])
index = ['A']

    def test_slice_dtype(dtype, index):
        result = _make_sliced_dtype(dtype, index)
        expected = np.ones((5, len(dtype)), dtype=dtype)[index].dtype
>       assert result == expected
E       AssertionError: assert dtype([('A', '<i4', (3, 2))]) == dtype({'names':['A'], 'formats':[('<i4', (3, 2))], 'offsets':[0], 'itemsize':48})

dask/array/tests/test_numpy_compat.py:39: AssertionError
__________________________________ test_basic __________________________________
[gw0] linux -- Python 3.6.4 /home/travis/miniconda/envs/test-environment/bin/python

    def test_basic():
        # sanity check
        dtype = [('a', 'f8'), ('b', 'f8'), ('c', 'f8')]
        x = np.ones((5, 3), dtype=dtype)
        dx = da.ones((5, 3), dtype=dtype, chunks=3)
        result = dx[['a', 'b']]
        expected = x[['a', 'b']]
>       assert_eq(result, expected)

dask/array/tests/test_numpy_compat.py:33: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

a = array([[(1., 1.), (1., 1.), (1., 1.)],
       [(1., 1.), (1., 1.), (1., 1.)],
       [(1., 1.), (1., 1.), (1., 1.)],
 ...., 1.), (1., 1.), (1., 1.)]],
      dtype={'names':['a','b'], 'formats':['<f8','<f8'], 'offsets':[0,8], 'itemsize':24})
b = array([[(1., 1.), (1., 1.), (1., 1.)],
       [(1., 1.), (1., 1.), (1., 1.)],
       [(1., 1.), (1., 1.), (1., 1.)],
 ...., 1.), (1., 1.), (1., 1.)]],
      dtype={'names':['a','b'], 'formats':['<f8','<f8'], 'offsets':[0,8], 'itemsize':24})
check_shape = True, kwargs = {}
a_original = dask.array<getitem, shape=(5, 3), dtype=[('a', '<f8'), ('b', '<f8')], chunksize=(3, 3)>
b_original = array([[(1., 1.), (1., 1.), (1., 1.)],
       [(1., 1.), (1., 1.), (1., 1.)],
       [(1., 1.), (1., 1.), (1., 1.)],
 ...., 1.), (1., 1.), (1., 1.)]],
      dtype={'names':['a','b'], 'formats':['<f8','<f8'], 'offsets':[0,8], 'itemsize':24})
adt = dtype([('a', '<f8'), ('b', '<f8')])

    def assert_eq(a, b, check_shape=True, **kwargs):
        a_original = a
        b_original = b
        if isinstance(a, Array):
            assert a.dtype is not None
            adt = a.dtype
            _check_dsk(a.dask)
            a = a.compute(get=get_sync)
            if hasattr(a, 'todense'):
                a = a.todense()
            if not hasattr(a, 'dtype'):
                a = np.array(a, dtype='O')
            if _not_empty(a):
>               assert a.dtype == a_original.dtype
E               AssertionError

dask/array/utils.py:86: AssertionError
_______________________ test_slice_dtype[dtype0-index1] ________________________
[gw1] linux -- Python 3.6.4 /home/travis/miniconda/envs/test-environment/bin/python

dtype = dtype([('A', '<f4', (3, 2)), ('B', '<f4', (3,)), ('C', '<f8', (3,))])
index = ['A', 'B']

    def test_slice_dtype(dtype, index):
        result = _make_sliced_dtype(dtype, index)
        expected = np.ones((5, len(dtype)), dtype=dtype)[index].dtype
>       assert result == expected
E       AssertionError: assert dtype([('A', '<f4', (3, 2)), ('B', '<f4', (3,))]) == dtype({'names':['A','B'], 'formats':[('<f4', (3, 2)),('<f4', (3,))], 'offsets':[0,24], 'itemsize':60})

dask/array/tests/test_numpy_compat.py:39: AssertionError
_______________________ test_slice_dtype[dtype1-index1] ________________________
[gw1] linux -- Python 3.6.4 /home/travis/miniconda/envs/test-environment/bin/python

dtype = dtype([('A', '<i4', (3, 2)), ('B', '<f4', (3,)), ('C', 'S4', (3,))])
index = ['A', 'B']

    def test_slice_dtype(dtype, index):
        result = _make_sliced_dtype(dtype, index)
        expected = np.ones((5, len(dtype)), dtype=dtype)[index].dtype
>       assert result == expected
E       AssertionError: assert dtype([('A', '<i4', (3, 2)), ('B', '<f4', (3,))]) == dtype({'names':['A','B'], 'formats':[('<i4', (3, 2)),('<f4', (3,))], 'offsets':[0,24], 'itemsize':48})

dask/array/tests/test_numpy_compat.py:39: AssertionError
_________________________ test_local[pyarrow-pyarrow] __________________________
[gw2] linux -- Python 3.6.4 /home/travis/miniconda/envs/test-environment/bin/python

tmpdir = local('/tmp/pytest-of-travis/pytest-0/popen-gw2/test_local_pyarrow_pyarrow_0')
write_engine = 'pyarrow', read_engine = 'pyarrow'

    @write_read_engines_xfail
    def test_local(tmpdir, write_engine, read_engine):
        tmp = str(tmpdir)
        data = pd.DataFrame({'i32': np.arange(1000, dtype=np.int32),
                             'i64': np.arange(1000, dtype=np.int64),
                             'f': np.arange(1000, dtype=np.float64),
                             'bhello': np.random.choice(['hello', 'yo', 'people'], size=1000).astype("O")})
        df = dd.from_pandas(data, chunksize=500)
    
        df.to_parquet(tmp, write_index=False, engine=write_engine)
    
        files = os.listdir(tmp)
        assert '_common_metadata' in files
        assert 'part.0.parquet' in files
    
        df2 = dd.read_parquet(tmp, index=False, engine=read_engine)
    
        assert len(df2.divisions) > 1
    
        out = df2.compute(get=dask.get).reset_index()
    
        for column in df.columns:
>           assert (data[column] == out[column]).all()

dask/dataframe/io/tests/test_parquet.py:115: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
../../../miniconda/envs/test-environment/lib/python3.6/site-packages/pandas/core/frame.py:2201: in __getitem__
    return self._getitem_column(key)
../../../miniconda/envs/test-environment/lib/python3.6/site-packages/pandas/core/frame.py:2208: in _getitem_column
    return self._get_item_cache(key)
../../../miniconda/envs/test-environment/lib/python3.6/site-packages/pandas/core/generic.py:2194: in _get_item_cache
    values = self._data.get(item)
../../../miniconda/envs/test-environment/lib/python3.6/site-packages/pandas/core/internals.py:4043: in get
    loc = self.items.get_loc(item)
../../../miniconda/envs/test-environment/lib/python3.6/site-packages/pandas/core/indexes/base.py:2638: in get_loc
    return self._engine.get_loc(self._maybe_cast_indexer(key))
pandas/_libs/index.pyx:139: in pandas._libs.index.IndexEngine.get_loc
    ???
pandas/_libs/index.pyx:161: in pandas._libs.index.IndexEngine.get_loc
    ???
pandas/_libs/hashtable_class_helper.pxi:1453: in pandas._libs.hashtable.PyObjectHashTable.get_item
    ???
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

>   ???
E   KeyError: 'bhello'

pandas/_libs/hashtable_class_helper.pxi:1461: KeyError
______________________ test_empty[pyarrow-pyarrow-False] _______________________
[gw2] linux -- Python 3.6.4 /home/travis/miniconda/envs/test-environment/bin/python

tmpdir = local('/tmp/pytest-of-travis/pytest-0/popen-gw2/test_empty_pyarrow_pyarrow_Fal0')
write_engine = 'pyarrow', read_engine = 'pyarrow', index = False

    @pytest.mark.parametrize('index', [False, True])
    @write_read_engines_xfail
    def test_empty(tmpdir, write_engine, read_engine, index):
        fn = str(tmpdir)
        df = pd.DataFrame({'a': ['a', 'b', 'b'], 'b': [4, 5, 6]})[:0]
        if index:
            df.set_index('a', inplace=True, drop=True)
        ddf = dd.from_pandas(df, npartitions=2)
    
        ddf.to_parquet(fn, write_index=index, engine=write_engine)
        read_df = dd.read_parquet(fn, engine=read_engine)
>       assert_eq(df, read_df)

dask/dataframe/io/tests/test_parquet.py:137: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
dask/dataframe/utils.py:581: in assert_eq
    tm.assert_frame_equal(a, b, **kwargs)
../../../miniconda/envs/test-environment/lib/python3.6/site-packages/pandas/util/testing.py:1268: in assert_frame_equal
    '{shape!r}'.format(shape=right.shape))
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

obj = 'DataFrame', message = 'DataFrame shape mismatch', left = '(0, 2)'
right = '(0, 0)', diff = None

    def raise_assert_detail(obj, message, left, right, diff=None):
        if isinstance(left, np.ndarray):
            left = pprint_thing(left)
        elif is_categorical_dtype(left):
            left = repr(left)
        if isinstance(right, np.ndarray):
            right = pprint_thing(right)
        elif is_categorical_dtype(right):
            right = repr(right)
    
        msg = """{obj} are different
    
    {message}
    [left]:  {left}
    [right]: {right}""".format(obj=obj, message=message, left=left, right=right)
    
        if diff is not None:
            msg += "\n[diff]: {diff}".format(diff=diff)
    
>       raise AssertionError(msg)
E       AssertionError: DataFrame are different
E       
E       DataFrame shape mismatch
E       [left]:  (0, 2)
E       [right]: (0, 0)

../../../miniconda/envs/test-environment/lib/python3.6/site-packages/pandas/util/testing.py:1008: AssertionError
________________________ test_no_index[pyarrow-pyarrow] ________________________
[gw2] linux -- Python 3.6.4 /home/travis/miniconda/envs/test-environment/bin/python

tmpdir = local('/tmp/pytest-of-travis/pytest-0/popen-gw2/test_no_index_pyarrow_pyarrow_0')
write_engine = 'pyarrow', read_engine = 'pyarrow'

    @write_read_engines_xfail
    def test_no_index(tmpdir, write_engine, read_engine):
        fn = str(tmpdir)
        df = pd.DataFrame({'a': [1, 2, 3], 'b': [4, 5, 6]})
        ddf = dd.from_pandas(df, npartitions=2)
        ddf.to_parquet(fn, write_index=False, engine=write_engine)
        ddf2 = dd.read_parquet(fn, engine=read_engine)
>       assert_eq(df, ddf2, check_index=False)

dask/dataframe/io/tests/test_parquet.py:255: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
dask/dataframe/utils.py:581: in assert_eq
    tm.assert_frame_equal(a, b, **kwargs)
../../../miniconda/envs/test-environment/lib/python3.6/site-packages/pandas/util/testing.py:1268: in assert_frame_equal
    '{shape!r}'.format(shape=right.shape))
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

obj = 'DataFrame', message = 'DataFrame shape mismatch', left = '(3, 2)'
right = '(0, 0)', diff = None

    def raise_assert_detail(obj, message, left, right, diff=None):
        if isinstance(left, np.ndarray):
            left = pprint_thing(left)
        elif is_categorical_dtype(left):
            left = repr(left)
        if isinstance(right, np.ndarray):
            right = pprint_thing(right)
        elif is_categorical_dtype(right):
            right = repr(right)
    
        msg = """{obj} are different
    
    {message}
    [left]:  {left}
    [right]: {right}""".format(obj=obj, message=message, left=left, right=right)
    
        if diff is not None:
            msg += "\n[diff]: {diff}".format(diff=diff)
    
>       raise AssertionError(msg)
E       AssertionError: DataFrame are different
E       
E       DataFrame shape mismatch
E       [left]:  (3, 2)
E       [right]: (0, 0)

../../../miniconda/envs/test-environment/lib/python3.6/site-packages/pandas/util/testing.py:1008: AssertionError
___________________________ test_to_hdf_lock_delays ____________________________
[gw0] linux -- Python 3.6.4 /home/travis/miniconda/envs/test-environment/bin/python

    @pytest.mark.slow
    def test_to_hdf_lock_delays():
        pytest.importorskip('tables')
        df16 = pd.DataFrame({'x': ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i',
                                   'j', 'k', 'l', 'm', 'n', 'o', 'p'],
                             'y': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14,
                                   15, 16]},
                            index=[1., 2., 3., 4., 5., 6., 7., 8., 9., 10., 11.,
                                   12., 13., 14., 15., 16.])
        a = dd.from_pandas(df16, 16)
    
        # adding artifichial delays to make sure last tasks finish first
        # that's a way to simulate last tasks finishing last
        def delayed_nop(i):
            if i[1] < 10:
                sleep(0.1 * (10 - i[1]))
            return i
    
        # saving to multiple hdf nodes
        with tmpfile() as fn:
            a = a.apply(delayed_nop, axis=1, meta=a)
>           a.to_hdf(fn, '/data*')

dask/dataframe/io/tests/test_hdf.py:283: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
dask/dataframe/core.py:1034: in to_hdf
    return to_hdf(self, path_or_buf, key, mode, append, get=get, **kwargs)
dask/dataframe/io/hdf.py:219: in to_hdf
    compute_as_if_collection(DataFrame, dsk, keys, get=get, **dask_kwargs)
dask/base.py:220: in compute_as_if_collection
    return get(dsk2, keys, **kwargs)
dask/threaded.py:75: in get
    pack_exception=pack_exception, **kwargs)
dask/local.py:521: in get_async
    raise_exception(exc, tb)
dask/compatibility.py:67: in reraise
    raise exc
dask/local.py:290: in execute_task
    result = _execute_task(task, data)
dask/local.py:271: in _execute_task
    return func(*args2)
dask/dataframe/core.py:3351: in apply_and_enforce
    df = func(*args, **kwargs)
dask/utils.py:687: in __call__
    return getattr(obj, self.method)(*args, **kwargs)
../../../miniconda/envs/test-environment/lib/python3.6/site-packages/pandas/core/frame.py:5000: in apply
    kwds=kwds)
../../../miniconda/envs/test-environment/lib/python3.6/site-packages/pandas/core/apply.py:29: in frame_apply
    args=args, kwds=kwds)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <pandas.core.apply.FrameColumnApply object at 0x7fc8802fa8d0>
obj =      x  y
1.0  a  1
func = <function test_to_hdf_lock_delays.<locals>.delayed_nop at 0x7fc87f5c19d8>
broadcast = False, raw = False, reduce = None, result_type = ()
ignore_failures = False, args = (), kwds = {}

    def __init__(self, obj, func, broadcast, raw, reduce, result_type,
                 ignore_failures, args, kwds):
        self.obj = obj
        self.raw = raw
        self.ignore_failures = ignore_failures
        self.args = args or ()
        self.kwds = kwds or {}
    
        if result_type not in [None, 'reduce', 'broadcast', 'expand']:
>           raise ValueError("invalid value for result_type, must be one "
                             "of {None, 'reduce', 'broadcast', 'expand'}")
E           ValueError: invalid value for result_type, must be one of {None, 'reduce', 'broadcast', 'expand'}

../../../miniconda/envs/test-environment/lib/python3.6/site-packages/pandas/core/apply.py:43: ValueError
__________________________________ test_apply __________________________________
[gw2] linux -- Python 3.6.4 /home/travis/miniconda/envs/test-environment/bin/python

    def test_apply():
        df = pd.DataFrame({'x': [1, 2, 3, 4], 'y': [10, 20, 30, 40]})
        ddf = dd.from_pandas(df, npartitions=2)
    
        func = lambda row: row['x'] + row['y']
        assert_eq(ddf.x.apply(lambda x: x + 1, meta=("x", int)),
                  df.x.apply(lambda x: x + 1))
    
        # specify meta
        assert_eq(ddf.apply(lambda xy: xy[0] + xy[1], axis=1, meta=(None, int)),
>                 df.apply(lambda xy: xy[0] + xy[1], axis=1))

dask/dataframe/tests/test_dataframe.py:1861: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
dask/dataframe/utils.py:565: in assert_eq
    assert_divisions(a)
dask/dataframe/utils.py:624: in assert_divisions
    results = get_sync(ddf.dask, ddf.__dask_keys__())
dask/local.py:562: in get_sync
    return get_async(apply_sync, 1, dsk, keys, **kwargs)
dask/local.py:508: in get_async
    fire_task()
dask/local.py:504: in fire_task
    callback=queue.put)
dask/local.py:551: in apply_sync
    res = func(*args, **kwds)
dask/local.py:295: in execute_task
    result = pack_exception(e, dumps)
dask/local.py:290: in execute_task
    result = _execute_task(task, data)
dask/local.py:271: in _execute_task
    return func(*args2)
dask/dataframe/core.py:3351: in apply_and_enforce
    df = func(*args, **kwargs)
dask/utils.py:687: in __call__
    return getattr(obj, self.method)(*args, **kwargs)
../../../miniconda/envs/test-environment/lib/python3.6/site-packages/pandas/core/frame.py:5000: in apply
    kwds=kwds)
../../../miniconda/envs/test-environment/lib/python3.6/site-packages/pandas/core/apply.py:29: in frame_apply
    args=args, kwds=kwds)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <pandas.core.apply.FrameColumnApply object at 0x7fbc7194e198>
obj =    x   y
2  3  30
3  4  40
func = <function test_apply.<locals>.<lambda> at 0x7fbc05e93730>
broadcast = False, raw = False, reduce = None, result_type = ()
ignore_failures = False, args = (), kwds = {}

    def __init__(self, obj, func, broadcast, raw, reduce, result_type,
                 ignore_failures, args, kwds):
        self.obj = obj
        self.raw = raw
        self.ignore_failures = ignore_failures
        self.args = args or ()
        self.kwds = kwds or {}
    
        if result_type not in [None, 'reduce', 'broadcast', 'expand']:
>           raise ValueError("invalid value for result_type, must be one "
                             "of {None, 'reduce', 'broadcast', 'expand'}")
E           ValueError: invalid value for result_type, must be one of {None, 'reduce', 'broadcast', 'expand'}

../../../miniconda/envs/test-environment/lib/python3.6/site-packages/pandas/core/apply.py:43: ValueError
___________________________ test_apply_infer_columns ___________________________
[gw2] linux -- Python 3.6.4 /home/travis/miniconda/envs/test-environment/bin/python

    def test_apply_infer_columns():
        df = pd.DataFrame({'x': [1, 2, 3, 4], 'y': [10, 20, 30, 40]})
        ddf = dd.from_pandas(df, npartitions=2)
    
        def return_df(x):
            # will create new DataFrame which columns is ['sum', 'mean']
            return pd.Series([x.sum(), x.mean()], index=['sum', 'mean'])
    
        # DataFrame to completely different DataFrame
        with pytest.warns(None):
            result = ddf.apply(return_df, axis=1)
        assert isinstance(result, dd.DataFrame)
        tm.assert_index_equal(result.columns, pd.Index(['sum', 'mean']))
>       assert_eq(result, df.apply(return_df, axis=1))

dask/dataframe/tests/test_dataframe.py:2089: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
dask/dataframe/utils.py:565: in assert_eq
    assert_divisions(a)
dask/dataframe/utils.py:624: in assert_divisions
    results = get_sync(ddf.dask, ddf.__dask_keys__())
dask/local.py:562: in get_sync
    return get_async(apply_sync, 1, dsk, keys, **kwargs)
dask/local.py:508: in get_async
    fire_task()
dask/local.py:504: in fire_task
    callback=queue.put)
dask/local.py:551: in apply_sync
    res = func(*args, **kwds)
dask/local.py:295: in execute_task
    result = pack_exception(e, dumps)
dask/local.py:290: in execute_task
    result = _execute_task(task, data)
dask/local.py:271: in _execute_task
    return func(*args2)
dask/dataframe/core.py:3351: in apply_and_enforce
    df = func(*args, **kwargs)
dask/utils.py:687: in __call__
    return getattr(obj, self.method)(*args, **kwargs)
../../../miniconda/envs/test-environment/lib/python3.6/site-packages/pandas/core/frame.py:5000: in apply
    kwds=kwds)
../../../miniconda/envs/test-environment/lib/python3.6/site-packages/pandas/core/apply.py:29: in frame_apply
    args=args, kwds=kwds)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <pandas.core.apply.FrameColumnApply object at 0x7fbc05f90908>
obj =    x   y
2  3  30
3  4  40
func = <function test_apply_infer_columns.<locals>.return_df at 0x7fbc0616a840>
broadcast = False, raw = False, reduce = None, result_type = ()
ignore_failures = False, args = (), kwds = {}

    def __init__(self, obj, func, broadcast, raw, reduce, result_type,
                 ignore_failures, args, kwds):
        self.obj = obj
        self.raw = raw
        self.ignore_failures = ignore_failures
        self.args = args or ()
        self.kwds = kwds or {}
    
        if result_type not in [None, 'reduce', 'broadcast', 'expand']:
>           raise ValueError("invalid value for result_type, must be one "
                             "of {None, 'reduce', 'broadcast', 'expand'}")
E           ValueError: invalid value for result_type, must be one of {None, 'reduce', 'broadcast', 'expand'}

../../../miniconda/envs/test-environment/lib/python3.6/site-packages/pandas/core/apply.py:43: ValueError
```

</details>

**Comment by mrocklin** [comment]
Some of those look like numpy 1.14.1 errors that were fixed (I thought) in https://github.com/dask/dask/pull/3187

**Comment by jakirkham** [comment]
Checked a [recent log]( https://travis-ci.org/dask/dask/jobs/350358773 ) to see if they were still present and the NumPy fields ones are still there. Everything else was not.

**Comment by mrocklin** [comment]
The numpy field access test has seen some churn recently.  I reverted a
change from a while ago for a recent version because it seemed that NumPy's
behavior changed.  See f98846e0c75ec5b4af897d143de140c220471773
