### ISSUE TITLE
CI test failures with pyarrow and hdfs

### ISSUE THREAD

**Issue by jakirkham** [dask/dask#3345]
Seeing this on CIs. Looks like a packaging issue actually as it is missing `boost`. Maybe related to PR ( https://github.com/conda-forge/parquet-cpp-feedstock/pull/43 ).

<details>

```python
=================================== FAILURES ===================================
_________________________ test_parquet_pyarrow[hdfs3] __________________________
mod_name = 'pyarrow', error_msg = '`pyarrow` not installed'
    def import_required(mod_name, error_msg):
        """Attempt to import a required dependency.
    
        Raises a RuntimeError if the requested module is not available.
        """
        try:
>           return import_module(mod_name)
dask/utils.py:92: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
name = 'pyarrow', package = None
    def import_module(name, package=None):
        """Import a module.
    
        The 'package' argument is required when performing a relative import. It
        specifies the package to use as the anchor point from which to resolve the
        relative import to an absolute import.
    
        """
        level = 0
        if name.startswith('.'):
            if not package:
                msg = ("the 'package' argument is required to perform a relative "
                       "import for {!r}")
                raise TypeError(msg.format(name))
            for character in name:
                if character != '.':
                    break
                level += 1
>       return _bootstrap._gcd_import(name[level:], package, level)
/opt/conda/lib/python3.6/importlib/__init__.py:126: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
name = 'pyarrow', package = None, level = 0
>   ???
<frozen importlib._bootstrap>:994: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
name = 'pyarrow', import_ = <function _gcd_import at 0x7f105ba66e18>
>   ???
<frozen importlib._bootstrap>:971: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
name = 'pyarrow', import_ = <function _gcd_import at 0x7f105ba66e18>
>   ???
<frozen importlib._bootstrap>:955: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
spec = ModuleSpec(name='pyarrow', loader=<_frozen_importlib_external.SourceFileLoader object at 0x7f102ff02c50>, origin='/opt...n3.6/site-packages/pyarrow/__init__.py', submodule_search_locations=['/opt/conda/lib/python3.6/site-packages/pyarrow'])
>   ???
<frozen importlib._bootstrap>:665: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
self = <_frozen_importlib_external.SourceFileLoader object at 0x7f102ff02c50>
module = <module 'pyarrow' from '/opt/conda/lib/python3.6/site-packages/pyarrow/__init__.py'>
>   ???
<frozen importlib._bootstrap_external>:678: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
f = <built-in function exec>
args = (<code object <module> at 0x7f102fef2c00, file "/opt/conda/lib/python3.6/site-packages/pyarrow/__init__.py", line 20>,...cached__': '/opt/conda/lib/python3.6/site-packages/pyarrow/__pycache__/__init__.cpython-36.pyc', '__doc__': None, ...})
kwds = {}
>   ???
<frozen importlib._bootstrap>:219: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
    from pkg_resources import get_distribution, DistributionNotFound
    try:
        __version__ = get_distribution(__name__).version
    except DistributionNotFound:
       # package is not installed
        try:
            # This code is duplicated from setup.py to avoid a dependency on each
            # other.
            def parse_version(root):
                from setuptools_scm import version_from_scm
                import setuptools_scm.git
                describe = (setuptools_scm.git.DEFAULT_DESCRIBE +
                            " --match 'apache-arrow-[0-9]*'")
                # Strip catchall from the commandline
                describe = describe.replace("--match *.*", "")
                version = setuptools_scm.git.parse(root, describe)
                if not version:
                    return version_from_scm(root)
                else:
                    return version
    
            import setuptools_scm
            __version__ = setuptools_scm.get_version('../', parse=parse_version)
        except (ImportError, LookupError):
            __version__ = None
    
    
>   from pyarrow.lib import cpu_count, set_cpu_count
E   ImportError: libboost_regex.so.1.66.0: cannot open shared object file: No such file or directory
/opt/conda/lib/python3.6/site-packages/pyarrow/__init__.py:47: ImportError
During handling of the above exception, another exception occurred:
hdfs = hdfs://localhost:8020, Connected
    @require_pyarrow
    def test_parquet_pyarrow(hdfs):
        dd = pytest.importorskip('dask.dataframe')
        import pandas as pd
        import numpy as np
    
        fn = '%s/test.parquet' % basedir
        hdfs_fn = 'hdfs://%s' % fn
        df = pd.DataFrame(np.random.normal(size=(1000, 4)),
                          columns=list('abcd'))
        ddf = dd.from_pandas(df, npartitions=4)
    
>       ddf.to_parquet(hdfs_fn, engine='pyarrow')
dask/bytes/tests/test_hdfs.py:245: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
dask/dataframe/core.py:1045: in to_parquet
    return to_parquet(self, path, *args, **kwargs)
dask/dataframe/io/parquet.py:892: in to_parquet
    write = get_engine(engine)['write']
dask/dataframe/io/parquet.py:749: in get_engine
    import_required('pyarrow', "`pyarrow` not installed")
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
mod_name = 'pyarrow', error_msg = '`pyarrow` not installed'
    def import_required(mod_name, error_msg):
        """Attempt to import a required dependency.
    
        Raises a RuntimeError if the requested module is not available.
        """
        try:
            return import_module(mod_name)
        except ImportError:
>           raise RuntimeError(error_msg)
E           RuntimeError: `pyarrow` not installed
dask/utils.py:94: RuntimeError
------------------------------ Captured log setup ------------------------------
core.py                    137 DEBUG    Connect to handle 94361929179216
=============== 1 failed, 10 passed, 13 skipped in 11.03 seconds ===============
The command "if [[ $TEST_HDFS == 'true' ]]; then source continuous_integration/hdfs/run_tests.sh; fi" exited with 1.
```

</details>

<br>

ref: https://travis-ci.org/dask/dask/jobs/359059325

**Comment by jakirkham** [comment]
Looking more closely it seems like these are using dev builds from `twosigma`. So the linked PR did not cause the issue. Though it may highlight what is going wrong. IOW the package now depends on Boost.Regex in shared library form, but doesn't explicitly list `boost` as dependency. May be fixed by listing the dependency or statically linking those pieces.

**Comment by mrocklin** [comment]
Perhaps we can go back to using more stable builds on conda-forge?

Also cc @wesm

**Comment by wesm** [comment]
Yes, you can use the 0.9.0 conda-forge binaries now. We need to fix the nightlies, though cc @cpcloud

**Comment by cpcloud** [comment]
The nightlies are working again, I fixed them yesterday or the day before: https://anaconda.org/twosigma/repo

**Comment by jakirkham** [comment]
[Still failing]( https://travis-ci.org/dask/dask/jobs/359412159 ) with the same issue as of an hour ago.

**Comment by jakirkham** [comment]
How would we like to proceed here?

**Comment by mrocklin** [comment]
Here is a [recent failure with the nightly pyarrow](https://travis-ci.org/dask/dask/jobs/362245521)

**Comment by cpcloud** [comment]
I can try to take a look at this today but I'm pretty swamped at work this week. I will have more time over the weekend to dig in.

**Comment by mrocklin** [comment]
It's not a blocker on any issues for us.  Our upstream-dev tests are
failing because of this, but they exist just to fail and give early warning
for problems like this one.

**Comment by mrocklin** [comment]
So from our perspective fixing would be great, but there's no immediate
time pressure.  Please don't spoil your weekend on our account.

**Comment by jakirkham** [comment]
Are we comfortable marking that test as a known failure?

**Comment by wesm** [comment]
@cpcloud @kszucs @pitrou any idea what's up with the nightlies here?

**Comment by pitrou** [comment]
I don't know. AFAIR we should not depend on `libboost_regex.so` anymore, but apparently our `CMakeLists.txt` still lists it?

**Comment by kszucs** [comment]
I've tried to reproduce the container. I don't know how much it helps, but here is the output:

```
$ docker run -it daskdev/dask-hdfs-testing:latest bash
```

Inside the container

```bash
root@40ddcccf0228:/working# conda install -y dask hdfs3 pyarrow -c twosigma -c conda-forge

Package plan for installation in environment /opt/conda:                                                                                                                                                                             [197/412]

The following NEW packages will be INSTALLED:

    arrow-cpp:        0.8.0+151.nightly-py36_2 twosigma
    bokeh:            0.12.15-py36_0           conda-forge
    click:            6.7-py_1                 conda-forge
    cloudpickle:      0.5.2-py_0               conda-forge
    cytoolz:          0.9.0.1-py36_0           conda-forge
    dask:             0.17.4-py_0              conda-forge
    dask-core:        0.17.4-py_0              conda-forge
    distributed:      1.21.8-py36_0            conda-forge
    hdfs3:            0.3.0-py36_0             conda-forge
    heapdict:         1.0.0-py36_0             conda-forge
    intel-openmp:     2018.0.0-8
    jinja2:           2.10-py36_0              conda-forge
    libgfortran-ng:   7.2.0-hdf63c60_3
    locket:           0.2.0-py36_1             conda-forge
    markupsafe:       1.0-py36_0               conda-forge
    mkl:              2018.0.2-1
    mkl_fft:          1.0.2-py36_0             conda-forge
    mkl_random:       1.0.1-py36_0             conda-forge
    msgpack-python:   0.5.6-py36_1             conda-forge
    numpy:            1.14.2-py36hdbf6ddf_1
    packaging:        17.1-py_0                conda-forge
    pandas:           0.22.0-py36_1            conda-forge
    parquet-cpp:      1.4.0+15.nightly-0       twosigma
    partd:            0.3.8-py36_0             conda-forge
    psutil:           5.4.5-py36_0             conda-forge
    pyarrow:          0.9.0+181.nightly-py36_1 twosigma
    pyparsing:        2.2.0-py36_0             conda-forge
    python-dateutil:  2.7.2-py_0               conda-forge
    pytz:             2018.4-py_0              conda-forge
    pyyaml:           3.12-py36_1              conda-forge
    sortedcontainers: 1.5.10-py36_0            conda-forge
    tblib:            1.3.2-py36_0             conda-forge
    toolz:            0.9.0-py_0               conda-forge
    tornado:          5.0.2-py36_0             conda-forge
    zict:             0.1.3-py_0               conda-forge

The following packages will be UPDATED:

    conda:            4.3.32-py36_0            conda-forge --> 4.5.3-py36_0 conda-forge

Installs successfully...

root@40ddcccf0228:/working# python -c "import pyarrow"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/opt/conda/lib/python3.6/site-packages/pyarrow/__init__.py", line 47, in <module>
    from pyarrow.lib import cpu_count, set_cpu_count
ImportError: libarrow.so.10: cannot open shared object file: No such file or directory

root@40ddcccf0228:/working# ls /opt/conda/lib/ | grep arrow
libarrow.a
libarrow.so
libarrow.so.0
libarrow.so.0.0.0
libarrow_python.a
libarrow_python.so
libarrow_python.so.0
libarrow_python.so.0.0.0
```

**Comment by cpcloud** [comment]
That looks screwy, and on my local machine I get matching versions.

**Comment by cpcloud** [comment]
Trying on the image now

**Comment by cpcloud** [comment]
the nightly build logs show that pyarrow is built against the correct, matching version of arrow-cpp that was built just before it, so i'm not sure what the issue is here.

additionally, updating conda using the `conda-forge` channel and *then* installing `pyarrow` as @kszucs shows above installs matching nightly `0.9.0`-based `pyarrow` and `arrow-cpp` builds.

importing pyarrow works after that.

hopefully we don't need to start sacrificing chickens and doing rain dances to make our software install correctly.

**Comment by jakirkham** [comment]
@kszucs, `conda` activation changes in 4.4.0+, which might be part of the issue that you are seeing there.

ref: https://github.com/conda/conda/releases/tag/4.4.0

**Comment by jakirkham** [comment]
That said, could be totally mistaken as we are seeing [the same issue in recent CI builds]( https://travis-ci.org/dask/dask/jobs/376423059#L700-L701 ).

**Comment by cpcloud** [comment]
@jakirkham, that build is installing conda <4.4.0

**Comment by jakirkham** [comment]
Seems to be [using 4.5.3]( https://travis-ci.org/dask/dask/jobs/376423059#L541 ).

**Comment by jakirkham** [comment]
Don't think that `conda` is the issue with the CI builds though. Checked locally already.

Though the error seems to be correct. How is the SONAME being set?

```bash
$ ls /opt/conda/lib/ | grep "libarrow.so*"
libarrow.so
libarrow.so.0
libarrow.so.0.0.0
```

**Comment by cpcloud** [comment]
@jakirkham, it matters that conda is updating *at the same time* as arrow is being installed. I don't know why. As I say above
> running conda update --all --yes -c conda-forge and then installing pyarrow

you must first update conda and then install arrow.

i don't think this is an SO issue, since conda is not installing the correct dependencies. it *does* install the correct dependencies when you first update conda and then install arrow

**Comment by cpcloud** [comment]
The SO version wasn't being set previously, and now it is as of [this PR](https://github.com/apache/arrow/pull/1975). Maybe that's related, but I'm not sure how that explains conda wanting to install mismatched versions.

**Comment by jakirkham** [comment]
Sorry, missed that. Though just updating `conda` in the Docker container alone seems to give me the same error, which is pretty odd.

**Comment by cpcloud** [comment]
Right, so the install only works correctly if you pass the `--all` flag *and* you install from `-c conda-forge`. I'm not sure how any of that affects how dependencies are calculated.

**Comment by jakirkham** [comment]
Yep, looking into it ATM. Think I have an idea.

**Comment by jakirkham** [comment]
Went ahead and just upgraded `conda` to `4.5.3` from `conda-forge` for what follows. Not sure if it is necessary to fix the issue, but it seems like a good idea given how old `conda` is in the image.

So it looks like there are two things that need to happen. There needs to be a newer copy of `boost-cpp` and a newer copy of `protobuf`. Upgrading both of these fixes the issue.

Weird side story, simply upgrading `boost-cpp` is not sufficient as `conda` pull in an ancient version of `boost` as well (details below). No idea why this happens. Any ideas, @kalefranz?

<details>

```bash
$ conda update -c conda-forge boost-cpp 
Solving environment: done

## Package Plan ##

  environment location: /opt/conda

  added / updated specs: 
    - boost-cpp


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    libhdfs3-2.2.31            |                0        19.4 MB  conda-forge
    boost-1.60.0               |           py36_0        10.5 MB
    ca-certificates-2018.4.16  |                0         139 KB  conda-forge
    certifi-2018.4.16          |           py36_0         142 KB  conda-forge
    boost-cpp-1.67.0           |                0        19.7 MB  conda-forge
    openssl-1.0.2o             |                0         3.5 MB  conda-forge
    ------------------------------------------------------------
                                           Total:        53.4 MB

The following NEW packages will be INSTALLED:

    boost:           1.60.0-py36_0                       

The following packages will be UPDATED:

    boost-cpp:       1.64.0-1                 conda-forge --> 1.67.0-0         conda-forge
    ca-certificates: 2017.08.26-h1d4fec5_0                --> 2018.4.16-0      conda-forge
    certifi:         2017.11.5-py36hf29ccca_0             --> 2018.4.16-py36_0 conda-forge
    openssl:         1.0.2n-hb7f436b_0                    --> 1.0.2o-0         conda-forge

The following packages will be DOWNGRADED:

    libhdfs3:        2.3-0                    conda-forge --> 2.2.31-0         conda-forge
```

</details>

<br>

Workaround is to install `boost`, which pulls in newer versions of `boost` and `boost-cpp`.

<details>

```bash
$  conda install -c conda-forge boost
Solving environment: done

## Package Plan ##

  environment location: /opt/conda

  added / updated specs: 
    - boost


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    intel-openmp-2018.0.0      |                8         620 KB
    openssl-1.0.2o             |                0         3.5 MB  conda-forge
    libhdfs3-2.3.0             |       h97226ba_1         8.4 MB
    boost-cpp-1.67.0           |                0        19.7 MB  conda-forge
    mkl_fft-1.0.2              |           py36_0         505 KB  conda-forge
    ca-certificates-2018.4.16  |                0         139 KB  conda-forge
    boost-1.67.0               |           py36_0         317 KB  conda-forge
    certifi-2018.4.16          |           py36_0         142 KB  conda-forge
    numpy-1.14.2               |   py36hdbf6ddf_1         4.1 MB
    mkl-2018.0.2               |                1       205.2 MB
    mkl_random-1.0.1           |           py36_0         1.3 MB  conda-forge
    libgfortran-ng-7.2.0       |       hdf63c60_3         1.2 MB
    libprotobuf-3.4.1          |       h5b8497f_0         4.0 MB
    ------------------------------------------------------------
                                           Total:       249.3 MB

The following NEW packages will be INSTALLED:

    boost:           1.67.0-py36_0            conda-forge
    intel-openmp:    2018.0.0-8                          
    libgfortran-ng:  7.2.0-hdf63c60_3                    
    libprotobuf:     3.4.1-h5b8497f_0                    
    mkl:             2018.0.2-1                          
    mkl_fft:         1.0.2-py36_0             conda-forge
    mkl_random:      1.0.1-py36_0             conda-forge
    numpy:           1.14.2-py36hdbf6ddf_1               

The following packages will be UPDATED:

    boost-cpp:       1.64.0-1                 conda-forge --> 1.67.0-0         conda-forge
    ca-certificates: 2017.08.26-h1d4fec5_0                --> 2018.4.16-0      conda-forge
    certifi:         2017.11.5-py36hf29ccca_0             --> 2018.4.16-py36_0 conda-forge
    libhdfs3:        2.3-0                    conda-forge --> 2.3.0-h97226ba_1            
    openssl:         1.0.2n-hb7f436b_0                    --> 1.0.2o-0         conda-forge
```

</details>

<br>

Of course that is not enough, we need to install `boost` and upgrade `protobuf`.

<details>

```bash
$  conda install -c conda-forge boost protobuf
Solving environment: done

## Package Plan ##

  environment location: /opt/conda

  added / updated specs: 
    - boost
    - protobuf


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    libgfortran-ng-7.2.0       |       hdf63c60_3         1.2 MB
    openssl-1.0.2o             |                0         3.5 MB  conda-forge
    mkl_random-1.0.1           |           py36_0         1.3 MB  conda-forge
    libprotobuf-3.5.2          |                0         4.5 MB  conda-forge
    ca-certificates-2018.4.16  |                0         139 KB  conda-forge
    libhdfs3-2.3               |                1         8.6 MB  conda-forge
    protobuf-3.5.2             |           py36_0         1.4 MB  conda-forge
    numpy-1.14.2               |   py36hdbf6ddf_1         4.1 MB
    boost-cpp-1.66.0           |                1        18.8 MB  conda-forge
    intel-openmp-2018.0.0      |                8         620 KB
    mkl-2018.0.2               |                1       205.2 MB
    mkl_fft-1.0.2              |           py36_0         505 KB  conda-forge
    boost-1.66.0               |           py36_1         317 KB  conda-forge
    certifi-2018.4.16          |           py36_0         142 KB  conda-forge
    ------------------------------------------------------------
                                           Total:       250.2 MB

The following NEW packages will be INSTALLED:

    boost:           1.66.0-py36_1            conda-forge
    intel-openmp:    2018.0.0-8                          
    libgfortran-ng:  7.2.0-hdf63c60_3                    
    libprotobuf:     3.5.2-0                  conda-forge
    mkl:             2018.0.2-1                          
    mkl_fft:         1.0.2-py36_0             conda-forge
    mkl_random:      1.0.1-py36_0             conda-forge
    numpy:           1.14.2-py36hdbf6ddf_1               

The following packages will be UPDATED:

    boost-cpp:       1.64.0-1                 conda-forge --> 1.66.0-1         conda-forge
    ca-certificates: 2017.08.26-h1d4fec5_0                --> 2018.4.16-0      conda-forge
    certifi:         2017.11.5-py36hf29ccca_0             --> 2018.4.16-py36_0 conda-forge
    libhdfs3:        2.3-0                    conda-forge --> 2.3-1            conda-forge
    openssl:         1.0.2n-hb7f436b_0                    --> 1.0.2o-0         conda-forge
    protobuf:        3.3.2-py36_0             conda-forge --> 3.5.2-py36_0     conda-forge
```

</details>

<br>

Once that is done installing `pyarrow` works smoothly and pulls in the right versions.

<details>

```bash
$  conda install -y dask hdfs3 pyarrow -c twosigma -c conda-forge
Solving environment: done

## Package Plan ##

  environment location: /opt/conda

  added / updated specs: 
    - dask
    - hdfs3
    - pyarrow


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    psutil-5.4.5               |           py36_0         332 KB  conda-forge
    pyarrow-0.9.0+181.nightly  |           py36_1         1.3 MB  twosigma
    packaging-17.1             |             py_0          20 KB  conda-forge
    pyyaml-3.12                |           py36_1         394 KB  conda-forge
    bokeh-0.12.15              |           py36_0         4.2 MB  conda-forge
    dask-core-0.17.4           |             py_0         440 KB  conda-forge
    click-6.7                  |             py_1          54 KB  conda-forge
    distributed-1.21.8         |           py36_0         765 KB  conda-forge
    heapdict-1.0.0             |           py36_0           5 KB  conda-forge
    msgpack-python-0.5.6       |   py36h2d50403_2         306 KB  conda-forge
    hdfs3-0.3.0                |           py36_0          38 KB  conda-forge
    cytoolz-0.9.0.1            |           py36_0         1.3 MB  conda-forge
    markupsafe-1.0             |           py36_0          32 KB  conda-forge
    partd-0.3.8                |           py36_0          29 KB  conda-forge
    tblib-1.3.2                |           py36_0          15 KB  conda-forge
    jinja2-2.10                |           py36_0         183 KB  conda-forge
    locket-0.2.0               |           py36_1           7 KB  conda-forge
    sortedcontainers-1.5.10    |           py36_0          45 KB  conda-forge
    cloudpickle-0.5.2          |             py_0          15 KB  conda-forge
    python-dateutil-2.7.2      |             py_0         203 KB  conda-forge
    arrow-cpp-0.9.0+181.nightly|           py36_7         4.3 MB  twosigma
    toolz-0.9.0                |             py_0          45 KB  conda-forge
    zict-0.1.3                 |             py_0          10 KB  conda-forge
    tornado-5.0.2              |           py36_0         657 KB  conda-forge
    pandas-0.22.0              |           py36_1        26.1 MB  conda-forge
    dask-0.17.4                |             py_0           2 KB  conda-forge
    parquet-cpp-1.4.0+15.nightly|                0         1.3 MB  twosigma
    pyparsing-2.2.0            |           py36_0          95 KB  conda-forge
    pytz-2018.4                |             py_0         215 KB  conda-forge
    ------------------------------------------------------------
                                           Total:        42.3 MB

The following NEW packages will be INSTALLED:

    arrow-cpp:        0.9.0+181.nightly-py36_7 twosigma   
    bokeh:            0.12.15-py36_0           conda-forge
    click:            6.7-py_1                 conda-forge
    cloudpickle:      0.5.2-py_0               conda-forge
    cytoolz:          0.9.0.1-py36_0           conda-forge
    dask:             0.17.4-py_0              conda-forge
    dask-core:        0.17.4-py_0              conda-forge
    distributed:      1.21.8-py36_0            conda-forge
    hdfs3:            0.3.0-py36_0             conda-forge
    heapdict:         1.0.0-py36_0             conda-forge
    jinja2:           2.10-py36_0              conda-forge
    locket:           0.2.0-py36_1             conda-forge
    markupsafe:       1.0-py36_0               conda-forge
    msgpack-python:   0.5.6-py36h2d50403_2     conda-forge
    packaging:        17.1-py_0                conda-forge
    pandas:           0.22.0-py36_1            conda-forge
    parquet-cpp:      1.4.0+15.nightly-0       twosigma   
    partd:            0.3.8-py36_0             conda-forge
    psutil:           5.4.5-py36_0             conda-forge
    pyarrow:          0.9.0+181.nightly-py36_1 twosigma   
    pyparsing:        2.2.0-py36_0             conda-forge
    python-dateutil:  2.7.2-py_0               conda-forge
    pytz:             2018.4-py_0              conda-forge
    pyyaml:           3.12-py36_1              conda-forge
    sortedcontainers: 1.5.10-py36_0            conda-forge
    tblib:            1.3.2-py36_0             conda-forge
    toolz:            0.9.0-py_0               conda-forge
    tornado:          5.0.2-py36_0             conda-forge
    zict:             0.1.3-py_0               conda-forge
```

</details>

<br>

Not sure where the Docker image is being maintained or who is maintaining it, but it looks like we need a rebuild.

**Comment by jakirkham** [comment]
That is the difference. Originally `boost` had everything, but users wanted to break out the C++ parts and depend on only them (if they didn't need `python` for instance). So we added `boost-cpp` with just the C++ parts. `boost` only packages the `python` parts since that split, but depends on `boost-cpp` in order to preserve the same user interface. There is a similar relationship between `libprotobuf` and `protobuf`.

**Comment by jakirkham** [comment]
Proposing we mark this test matrix item as a know failure until someone has time to fix it. ( https://github.com/dask/dask/pull/3626 )

**Comment by wesm** [comment]
Any actions we can take on the Arrow side to help with this?

**Comment by jakirkham** [comment]
The main issue is the Docker image used for this test needs to be rebuilt with newer packages. @mrocklin, any idea how we can make this happen?
