### ISSUE TITLE
masked array not serialize properly in cluster,

### ISSUE THREAD

**Issue by dnadeau4** [dask/dask#4225]
Somehow the `numpy.ma` `serializer` is not called while using `LocalCluster` and we get the noxious `fill_value` error when calling `dumps`.    I could not find out exactly where it happens.  

**Without using `dask.distributed` everything works fine.**

# Code
```python
import dask.array as da
import numpy as np
import numpy.ma as ma
from dask.distributed import LocalCluster
from dask.distributed import Client
cluster=LocalCluster(n_workers=12,threads_per_worker=1)
c=Client(cluster)
my_arr = np.ones((10),dtype='float32')
my_mask = [True, True, True, True, True, True, True, True, True, True]
my_masked_arr = np.ma.MaskedArray(my_arr, mask=my_mask,fill_value=1e20)

my_masked_dask_arr = da.ma.masked_array(my_masked_arr)
print("dask masked avg: ", my_masked_dask_arr.mean().compute())
```

# Error
```
File ".../distributed/protocol/core.py", line 94, in dumps
    msgpack.dumps(header, use_bin_type=True)] + out_frames
  File ".../lib/python3.6/site-packages/msgpack/__init__.py", line 47, in packb
    return Packer(**kwargs).pack(o)
  File "msgpack/_packer.pyx", line 284, in msgpack._packer.Packer.pack
...
  File "msgpack/_packer.pyx", line 281, in msgpack._packer.Packer._pack
TypeError: can't serialize 1e+20
TypeError: can't serialize 1e+20
```
  
# Without `distributed cluster`
```python
import dask.array as da
import numpy as np
import numpy.ma as ma

my_arr = np.ones((10),dtype='float32')*1e20
my_mask = [True, True, True, True, True, True, True, True, True, True]
my_masked_arr = np.ma.MaskedArray(my_arr, mask=my_mask,fill_value=1e20)

my_masked_dask_arr = da.ma.masked_array(my_masked_arr)
print("dask masked avg: ", my_masked_dask_arr.mean().compute())
```
## Result masked correctly. 😏 
```
dask masked avg:  --
```

**Comment by jcrist** [comment]
Should be fixed by https://github.com/dask/distributed/pull/2373

**Comment by dnadeau4** [comment]
@jcrist for some reason my first example in section `CODE` still fail.  I tried to add my array in `test_numpy.py` and it worked, but I don't know if the `cluster` has been generated. 

Here is the new error I get.

## ERROR
```
  File "./distributed/protocol/serialize.py", line 139, in serialize
    header, frames = dumps(x, context=context) if wants_context else dumps(x)
  File "./distributed/protocol/serialize.py", line 39, in dask_dumps
    header, frames = dumps(x)
  File "./distributed/protocol/numpy.py", line 119, in serialize_numpy_maskedarray
    if isinstance(x.fill_value, (np.integer, np.floating, np.bool_)):
  File ".../miniconda3/envs/dask-scipy/lib/python3.6/site-packages/numpy/ma/core.py", line 3609, in get_fill_value
    self._fill_value = _check_fill_value(None, self.dtype)
  File ".../miniconda3/envs/dask-scipy/lib/python3.6/site-packages/numpy/ma/core.py", line 6341, in __setattr__
    "attributes of {!r} are not writeable".format(self))
AttributeError: attributes of masked are not writeable
```

**Comment by dnadeau4** [comment]
@mrocklin The example in the section above, still does not work for me and I have a new error.  Could you give it a try?

https://github.com/dask/dask/issues/4225#issue-382053414

**Comment by mrocklin** [comment]
I suspect that you meant to cc @jcrist or @dkillick who have actually been the ones working to resolve this problem.

**Comment by dnadeau4** [comment]
@mrocklin `github` said that you closed the issue, that is why I mentioned you.  I checked out the `PR#` and then `master` and It seems that `serialize_numpy_maskedarray` is not working with my example.

**Comment by jcrist** [comment]
@dnadeau4, I am unable to reproduce with the fix in https://github.com/dask/distributed/pull/2373, are you sure you're using the most recent master branch of distributed?

```python
In [1]: %load test.py

In [2]: # %load test.py
   ...: import dask.array as da
   ...: import numpy as np
   ...: import numpy.ma as ma
   ...: from dask.distributed import LocalCluster
   ...: from dask.distributed import Client
   ...:
   ...: if __name__ == '__main__':
   ...:     cluster = LocalCluster(n_workers=12,threads_per_worker=1)
   ...:     c = Client(cluster)
   ...:     my_arr = np.ones((10),dtype='float32')
   ...:     my_mask = [True, True, True, True, True, True, True, True, True, True]
   ...:     my_masked_arr = np.ma.MaskedArray(my_arr, mask=my_mask,fill_value=1e20)
   ...:
   ...:     my_masked_dask_arr = da.ma.masked_array(my_masked_arr)
   ...:     print("dask masked avg: ", my_masked_dask_arr.mean().compute())
   ...:
dask masked avg:  --
```

**Comment by dnadeau4** [comment]
Here are the packages I am using.  I tried on the `OSX` and `Linux` and got the same issue.
```
python                    2.7.15               h1571d57_0
numpy                     1.15.1           py27h1d66e8a_0  
numpy-base                1.15.1           py27h81de0dd_0  
distributed               1.25.0                    <pip>
dask                      0.20.1                    <pip>
dask-core                 0.19.0                     py_0    conda-forge
dask-kubernetes           0.5.0                     <pip>
distarray                 2.12.2                   py27_0    conda-forge
tornado                   5.1              py27h470a237_1    conda-forge
```

**Comment by jcrist** [comment]
Ok, I'm able to reproduce, and have diagnosed the issue. Passes in numpy 1.14, fails in numpy 1.15, due to `masked` object type changing implementation. This is fixable, but I don't plan to tackle it tonight (it's late here). Should have a fix tomorrow.

**Comment by jcrist** [comment]
Fixed by #2384:


```console
$ cat test.py
from __future__ import print_function
import dask.array as da
import numpy as np
import numpy.ma as ma
from dask.distributed import LocalCluster
from dask.distributed import Client

print("numpy: %s" % np.__version__)

with Client(n_workers=2, threads_per_worker=1) as client:
    my_arr = np.ones((10),dtype='float32')
    my_mask = [True, True, True, True, True, True, True, True, True, True]
    my_masked_arr = np.ma.MaskedArray(my_arr, mask=my_mask,fill_value=1e20)

    my_masked_dask_arr = da.ma.masked_array(my_masked_arr)
    print("dask masked avg: %r" % my_masked_dask_arr.mean().compute())
$ python test.py
numpy: 1.15.1
dask masked avg: masked
```

**Comment by dnadeau4** [comment]
works very well for me now. 😄
