### ISSUE TITLE
Support StringDtype in `str.extract` (and probably elsewhere)

### ISSUE THREAD

**Issue by gerritholl** [dask/dask#5833]
More of a feature request than a bug report: I'd like to have support for pandas new `StringDtype` extension dtype for string operations.

Test script:

```python
import pandas as pd
import dask.dataframe as ddf
import os
import io
import tempfile
s=""",DATE,VIS
0,2019-01-03 22:00:00,"025000,1,9,9"
1,2019-01-04 04:00:00,"025000,1,9,9"
2,2019-01-04 22:00:00,"020000,1,9,9"
3,2019-01-05 22:00:00,"000100,1,9,9"
4,2019-01-08 04:00:00,"025000,1,9,9"
"""
df1 = pd.read_csv(io.StringIO(s), dtype={"STATION": pd.StringDtype()}, parse_dates=["DATE"])
# dask's read_csv can't read from stream
with tempfile.NamedTemporaryFile(suffix=".csv", mode="w+t", encoding="ascii",
        delete=False) as ntf:
    ntf.write(s)
df2 = ddf.read_csv(ntf.name, dtype={"VIS": pd.StringDtype()}, parse_dates=["DATE"])
try:
    vis1 = df1.VIS.str.extract(r"(\d{6}),(\d),([NV9]),(\d)")
    vis2 = df2.VIS.str.extract(r"(\d{6}),(\d),([NV9]),(\d)").compute()
finally:
    os.unlink(ntf.name)
```

Fails with:

```
Traceback (most recent call last):
  File "mwe18.py", line 21, in <module>
    vis2 = df2.VIS.str.extract(r"(\d{6}),(\d),([NV9]),(\d)").compute()
  File "/media/nas/x21324/miniconda3/envs/py37e/lib/python3.7/site-packages/dask/dataframe/accessor.py", line 64, in _function_map
    self._series._meta_nonempty, self._accessor_name, attr, args, kwargs
  File "/media/nas/x21324/miniconda3/envs/py37e/lib/python3.7/site-packages/dask/dataframe/core.py", line 344, in _meta_nonempty
    return meta_nonempty(self._meta)
  File "/media/nas/x21324/miniconda3/envs/py37e/lib/python3.7/site-packages/dask/utils.py", line 505, in __call__
    return meth(arg, *args, **kwargs)
  File "/media/nas/x21324/miniconda3/envs/py37e/lib/python3.7/site-packages/dask/dataframe/utils.py", line 575, in _nonempty_series
    data = np.array([entry, entry], dtype=dtype)
TypeError: data type not understood
```

On dask 2.9.2 with pandas 1.0.0rc0.  Full details of environment:

<details>
# packages in environment at /media/nas/x21324/miniconda3/envs/py37e:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                 conda_forge    conda-forge
_openmp_mutex             4.5                       0_gnu    conda-forge
affine                    2.3.0                      py_0    conda-forge
aggdraw                   1.3.11           py37hc56bac0_0    conda-forge
alabaster                 0.7.12                     py_0    conda-forge
appdirs                   1.4.3                    pypi_0    pypi
arrow-cpp                 0.15.1           py37had5782a_4    conda-forge
asciitree                 0.3.3                      py_2    conda-forge
attrs                     19.3.0                     py_0    conda-forge
awscli                    1.17.8                   py37_0    conda-forge
babel                     2.8.0                      py_0    conda-forge
backcall                  0.1.0                      py_0    conda-forge
beautifulsoup4            4.8.2                    py37_0    conda-forge
behave                    1.2.6                 py37_1000    conda-forge
bitstring                 3.1.6                    pypi_0    pypi
bleach                    3.1.0                      py_0    conda-forge
blosc                     1.17.0               he1b5a44_1    conda-forge
bokeh                     1.4.0                    py37_0    conda-forge
boost-cpp                 1.70.0               h8e57a91_2    conda-forge
boto3                     1.11.8                     py_0    conda-forge
botocore                  1.14.8                     py_0    conda-forge
brotli                    1.0.7             he1b5a44_1000    conda-forge
bzip2                     1.0.8                h516909a_2    conda-forge
c-ares                    1.15.0            h516909a_1001    conda-forge
ca-certificates           2019.11.28           hecc5488_0    conda-forge
cairo                     1.16.0            hfb77d84_1002    conda-forge
cartopy                   0.17.0          py37hc5b2455_1008    conda-forge
certifi                   2019.11.28               py37_0    conda-forge
cffi                      1.13.2           py37h8022711_0    conda-forge
cfgrib                    0.9.7.3                    py_0    conda-forge
cfitsio                   3.470                hb60a0a2_2    conda-forge
cftime                    1.0.4.2          py37hc1659b7_0    conda-forge
chardet                   3.0.4                 py37_1003    conda-forge
click                     7.0                        py_0    conda-forge
click-plugins             1.1.1                      py_0    conda-forge
cligj                     0.5.0                      py_0    conda-forge
cloudpickle               1.2.2                      py_1    conda-forge
codecov                   2.0.15                     py_1    conda-forge
colorama                  0.4.1                      py_0    conda-forge
colorcet                  2.0.1                      py_0    conda-forge
configobj                 5.0.6                      py_0    conda-forge
coverage                  5.0.3            py37h516909a_0    conda-forge
coveralls                 1.10.0                     py_0    conda-forge
cryptography              2.8              py37h72c5cf5_1    conda-forge
curl                      7.65.3               hf8cf82a_0    conda-forge
cycler                    0.10.0                     py_2    conda-forge
cython                    0.29.14          py37he1b5a44_0    conda-forge
cytoolz                   0.10.1           py37h516909a_0    conda-forge
dask                      2.9.2                      py_0    conda-forge
dask-core                 2.9.2                      py_0    conda-forge
datashader                0.8.0                      py_0    conda-forge
datashape                 0.5.4                      py_1    conda-forge
dbus                      1.13.6               he372182_0    conda-forge
decorator                 4.4.1                      py_0    conda-forge
defusedxml                0.6.0                      py_0    conda-forge
distributed               2.9.3                      py_0    conda-forge
docopt                    0.6.2                      py_1    conda-forge
docutils                  0.15.2                   py37_0    conda-forge
double-conversion         3.1.5                he1b5a44_2    conda-forge
eccodes                   2.14.1               hc4140ea_3    conda-forge
entrypoints               0.3                   py37_1000    conda-forge
expat                     2.2.5             he1b5a44_1004    conda-forge
fasteners                 0.14.1                     py_3    conda-forge
fcitools                  0.1.0.post0.dev5+ga19d0d1          pypi_0    pypi
fiona                     1.8.13           py37h900e953_0    conda-forge
flake8                    3.7.9                    py37_0    conda-forge
fogpy                     1.2.0+dev21.g2b0d49d.get.validation.output.for.fog.mask          pypi_0    pypi
fogtools                  0.0.post0.dev13+g735723f.dirty           dev_0    <develop>
fontconfig                2.13.1            h86ecdb6_1001    conda-forge
freetype                  2.10.0               he983fc9_1    conda-forge
freetype-py               2.1.0.post1                py_0    conda-forge
freexl                    1.0.5             h14c3975_1002    conda-forge
fsspec                    0.6.2                      py_0    conda-forge
g2clib                    1.6.0                hf3f1b0b_9    conda-forge
gdal                      3.0.2            py37hbb6b9fb_3    conda-forge
geopandas                 0.6.2                      py_0    conda-forge
geos                      3.7.2                he1b5a44_2    conda-forge
geotiff                   1.5.1                hbd99317_7    conda-forge
geoviews                  1.6.5                      py_0    conda-forge
geoviews-core             1.6.5                      py_0    conda-forge
gettext                   0.19.8.1          hc5be6a0_1002    conda-forge
gflags                    2.2.2             he1b5a44_1002    conda-forge
giflib                    5.1.7                h516909a_1    conda-forge
glib                      2.58.3          py37h6f030ca_1002    conda-forge
glog                      0.4.0                he1b5a44_1    conda-forge
goesr                     0.5.2                    pypi_0    pypi
grpc-cpp                  1.25.0               h5321d42_1    conda-forge
gst-plugins-base          1.14.5               h0935bb2_0    conda-forge
gstreamer                 1.14.5               h36ae1b5_0    conda-forge
h5netcdf                  0.7.4                      py_0    conda-forge
h5py                      2.10.0          nompi_py37h513d04c_101    conda-forge
hdf4                      4.2.13            hf30be14_1003    conda-forge
hdf5                      1.10.5          nompi_h3c11f04_1104    conda-forge
hdfeos2                   2.20              h64bfcee_1000    conda-forge
hdfeos5                   5.1.16               h8b6279f_5    conda-forge
heapdict                  1.0.1                      py_0    conda-forge
holoviews                 1.12.7                     py_0    conda-forge
icu                       64.2                 he1b5a44_1    conda-forge
idna                      2.8                   py37_1000    conda-forge
imageio                   2.6.1                    py37_0    conda-forge
imagesize                 1.2.0                      py_0    conda-forge
importlib_metadata        1.4.0                    py37_0    conda-forge
ipdb                      0.12.3                     py_0    conda-forge
ipykernel                 5.1.3            py37h5ca1d4c_0    conda-forge
ipython                   7.11.1           py37h5ca1d4c_0    conda-forge
ipython_genutils          0.2.0                      py_1    conda-forge
ipywidgets                7.5.1                      py_0    conda-forge
jasper                    1.900.1           h07fcdf6_1006    conda-forge
jedi                      0.15.2                   py37_0    conda-forge
jinja2                    2.10.3                     py_0    conda-forge
jmespath                  0.9.4                      py_0    conda-forge
jpeg                      9c                h14c3975_1001    conda-forge
json-c                    0.13.1            h14c3975_1001    conda-forge
jsonschema                3.2.0                    py37_0    conda-forge
jupyter                   1.0.0                      py_2    conda-forge
jupyter_client            5.3.4                    py37_1    conda-forge
jupyter_console           6.0.0                      py_0    conda-forge
jupyter_core              4.6.1                    py37_0    conda-forge
kealib                    1.4.10            h58c409b_1005    conda-forge
kiwisolver                1.1.0            py37hc9558a2_0    conda-forge
krb5                      1.16.4               h2fd8d38_0    conda-forge
ld_impl_linux-64          2.33.1               h53a641e_7    conda-forge
libaec                    1.0.4                hf484d3e_0    conda-forge
libblas                   3.8.0               14_openblas    conda-forge
libcblas                  3.8.0               14_openblas    conda-forge
libclang                  9.0.1           default_hde54327_0    conda-forge
libcurl                   7.65.3               hda55be3_0    conda-forge
libdap4                   3.20.4               hd3bb157_0    conda-forge
libedit                   3.1.20170329      hf8c457e_1001    conda-forge
libevent                  2.1.10               h72c5cf5_0    conda-forge
libffi                    3.2.1             he1b5a44_1006    conda-forge
libgcc-ng                 9.2.0                h24d8f2e_2    conda-forge
libgdal                   3.0.2                h5534617_3    conda-forge
libgfortran-ng            7.3.0                hdf63c60_4    conda-forge
libgomp                   9.2.0                h24d8f2e_2    conda-forge
libiconv                  1.15              h516909a_1005    conda-forge
libkml                    1.3.0             h4fcabce_1010    conda-forge
liblapack                 3.8.0               14_openblas    conda-forge
libllvm8                  8.0.1                hc9558a2_0    conda-forge
libllvm9                  9.0.1                hc9558a2_0    conda-forge
libnetcdf                 4.7.1           nompi_h94020b1_102    conda-forge
libopenblas               0.3.7                h5ec1e0e_6    conda-forge
libpng                    1.6.37               hed695b0_0    conda-forge
libpq                     11.5                 hd9ab2ff_2    conda-forge
libprotobuf               3.10.1               h8b12597_0    conda-forge
libsodium                 1.0.17               h516909a_0    conda-forge
libspatialindex           1.9.3                he1b5a44_1    conda-forge
libspatialite             4.3.0a            h4f6d029_1032    conda-forge
libssh2                   1.8.2                h22169c7_2    conda-forge
libstdcxx-ng              9.2.0                hdf63c60_2    conda-forge
libtiff                   0.4.2                    pypi_0    pypi
libuuid                   2.32.1            h14c3975_1000    conda-forge
libwebp                   1.0.2                hf4e8a37_4    conda-forge
libxcb                    1.13              h14c3975_1002    conda-forge
libxkbcommon              0.9.1                hebb1f50_0    conda-forge
libxml2                   2.9.10               hee79883_0    conda-forge
libxslt                   1.1.33               h31b3aaa_0    conda-forge
line_profiler             3.0.2            py37hc9558a2_0    conda-forge
llvmlite                  0.31.0           py37h8b12597_0    conda-forge
locket                    0.2.0                      py_2    conda-forge
lxml                      4.4.2            py37h7ec2d77_0    conda-forge
lz4-c                     1.8.3             he1b5a44_1001    conda-forge
lzo                       2.10              h14c3975_1000    conda-forge
markupsafe                1.1.1            py37h516909a_0    conda-forge
matplotlib                3.1.2                    py37_1    conda-forge
matplotlib-base           3.1.2            py37h250f245_1    conda-forge
mccabe                    0.6.1                      py_1    conda-forge
mechanicalsoup            0.12.0                     py_0    conda-forge
mistune                   0.8.4           py37h516909a_1000    conda-forge
mock                      3.0.5                    py37_0    conda-forge
monotonic                 1.5                        py_0    conda-forge
more-itertools            8.1.0                      py_0    conda-forge
msgpack-python            0.6.2            py37hc9558a2_0    conda-forge
multipledispatch          0.6.0                      py_0    conda-forge
munch                     2.5.0                      py_0    conda-forge
nbconvert                 5.6.1                    py37_0    conda-forge
nbformat                  5.0.4                      py_0    conda-forge
ncurses                   6.1               hf484d3e_1002    conda-forge
netcdf4                   1.5.3           nompi_py37hfee4bf2_101    conda-forge
networkx                  2.4                        py_0    conda-forge
notebook                  6.0.3                    py37_0    conda-forge
nspr                      4.24                 he1b5a44_0    conda-forge
nss                       3.47                 he751ad9_0    conda-forge
numba                     0.47.0           py37hb3f55d8_0    conda-forge
numcodecs                 0.6.4            py37he1b5a44_0    conda-forge
numexpr                   2.7.1            py37hb3f55d8_0    conda-forge
numpy                     1.17.5           py37h95a1406_0    conda-forge
olefile                   0.46                       py_0    conda-forge
opencv-python             4.1.0.25                 pypi_0    pypi
openjpeg                  2.3.1                h981e76c_3    conda-forge
openssl                   1.1.1d               h516909a_0    conda-forge
owslib                    0.19.0                     py_2    conda-forge
packaging                 20.0                       py_0    conda-forge
pandas                    1.0.0rc0                 pypi_0    pypi
pandoc                    2.9.1.1                       0    conda-forge
pandocfilters             1.4.2                      py_1    conda-forge
param                     1.9.2                      py_0    conda-forge
parquet-cpp               1.5.1                         2    conda-forge
parse                     1.14.0                     py_0    conda-forge
parse_type                0.5.2                    py37_0    conda-forge
parso                     0.5.2                      py_0    conda-forge
partd                     1.1.0                      py_0    conda-forge
pcre                      8.43                 he1b5a44_0    conda-forge
pexpect                   4.8.0                    py37_0    conda-forge
pickleshare               0.7.5                 py37_1000    conda-forge
pillow                    7.0.0            py37hefe7db6_0    conda-forge
pip                       20.0.1                   py37_0    conda-forge
pixman                    0.38.0            h516909a_1003    conda-forge
pluggy                    0.13.0                   py37_0    conda-forge
poppler                   0.67.0               h14e79db_8    conda-forge
poppler-data              0.4.9                         1    conda-forge
postgresql                11.5                 hc63931a_2    conda-forge
progressbar2              3.47.0                     py_0    conda-forge
proj                      6.2.1                hc80f0dc_0    conda-forge
prometheus_client         0.7.1                      py_0    conda-forge
prompt_toolkit            2.0.10                     py_0    conda-forge
psutil                    5.6.7            py37h516909a_0    conda-forge
pthread-stubs             0.4               h14c3975_1001    conda-forge
ptyprocess                0.6.0                   py_1001    conda-forge
py                        1.8.1                      py_0    conda-forge
pyarrow                   0.15.1           py37h8b68381_1    conda-forge
pyasn1                    0.4.8                      py_0    conda-forge
pycoast                   1.3.2                      py_0    conda-forge
pycodestyle               2.5.0                      py_0    conda-forge
pycparser                 2.19                     py37_1    conda-forge
pyct                      0.4.6                      py_0    conda-forge
pyct-core                 0.4.6                      py_0    conda-forge
pydap                     3.2.2                 py37_1000    conda-forge
pydecorate                0.2.1                      py_0    conda-forge
pyepsg                    0.4.0                      py_0    conda-forge
pyflakes                  2.1.1                      py_0    conda-forge
pygments                  2.5.2                      py_0    conda-forge
pygrib                    2.0.4            py37h55c65ac_0    conda-forge
pyhdf                     0.10.2           py37h3a4e923_0    conda-forge
pykdtree                  1.3.1           py37hc1659b7_1002    conda-forge
pynio                     1.5.5            py37h2e5bc1a_7    conda-forge
pyopengl                  3.1.5                      py_0    conda-forge
pyopenssl                 19.1.0                   py37_0    conda-forge
pyorbital                 1.5.0                    pypi_0    pypi
pyparsing                 2.4.6                      py_0    conda-forge
pyproj                    2.4.2.post1      py37h12732c1_0    conda-forge
pyqt                      5.12.3           py37hcca6a23_1    conda-forge
pyqt5                     5.13.1                   pypi_0    pypi
pyqt5-sip                 4.19.18                  pypi_0    pypi
pyqtgraph                 0.11.0rc0                  py_0    conda-forge
pyqtwebengine             5.12.1                   pypi_0    pypi
pyresample                1.14.0           py37hb3f55d8_2    conda-forge
pyrsistent                0.15.7           py37h516909a_0    conda-forge
pyscaffold                3.2.2                      py_0    conda-forge
pyshp                     2.1.0                      py_0    conda-forge
pysocks                   1.7.1                    py37_0    conda-forge
pyspectral                0.8.9                    pypi_0    pypi
pytables                  3.6.1            py37h9f153d1_1    conda-forge
pytest                    5.3.4                    py37_0    conda-forge
pytest-cov                2.8.1                      py_0    conda-forge
pytest-mock               2.0.0                    py37_0    conda-forge
pytest-runner             5.2                        py_0    conda-forge
python                    3.7.6                h357f687_2    conda-forge
python-dateutil           2.8.1                      py_0    conda-forge
python-geotiepoints       1.1.8                    pypi_0    pypi
python-utils              2.3.0                      py_1    conda-forge
pytz                      2019.3                     py_0    conda-forge
pyviz_comms               0.7.3                      py_0    conda-forge
pywavelets                1.1.1            py37hc1659b7_0    conda-forge
pyyaml                    5.2              py37h516909a_0    conda-forge
pyzmq                     18.1.1           py37h1768529_0    conda-forge
qt                        5.12.5               hd8c4c69_1    conda-forge
qtconsole                 4.6.0                      py_0    conda-forge
quamash                   0.6.1                    pypi_0    pypi
rasterio                  1.1.1            py37h900e953_0    conda-forge
re2                       2020.01.01           he1b5a44_0    conda-forge
readline                  8.0                  hf8c457e_0    conda-forge
requests                  2.22.0                   py37_1    conda-forge
rsa                       3.4.2                      py_1    conda-forge
rtree                     0.9.3            py37h7b0cdae_0    conda-forge
s3fs                      0.4.0                      py_0    conda-forge
s3transfer                0.3.2                    py37_0    conda-forge
satpy                     0.19.2.dev31+gf537a14d          pypi_0    pypi
scikit-image              0.16.2           py37hb3f55d8_0    conda-forge
scipy                     1.4.1            py37h921218d_0    conda-forge
send2trash                1.5.0                      py_0    conda-forge
setuptools                45.1.0                   py37_0    conda-forge
shapely                   1.6.4           py37hec07ddf_1006    conda-forge
six                       1.14.0                   py37_0    conda-forge
snakeviz                  2.0.1                      py_0    conda-forge
snappy                    1.1.7             he1b5a44_1003    conda-forge
snowballstemmer           2.0.0                      py_0    conda-forge
snuggs                    1.4.7                      py_0    conda-forge
sortedcontainers          2.1.0                      py_0    conda-forge
soupsieve                 1.9.4                    py37_0    conda-forge
sphinx                    2.3.1                      py_0    conda-forge
sphinxcontrib-applehelp   1.0.1                      py_0    conda-forge
sphinxcontrib-devhelp     1.0.1                      py_0    conda-forge
sphinxcontrib-htmlhelp    1.0.2                      py_0    conda-forge
sphinxcontrib-jsmath      1.0.1                      py_0    conda-forge
sphinxcontrib-qthelp      1.0.2                      py_0    conda-forge
sphinxcontrib-serializinghtml 1.1.3                      py_0    conda-forge
sqlalchemy                1.3.13           py37h516909a_0    conda-forge
sqlite                    3.30.1               hcee41ef_0    conda-forge
tbb                       2018.0.5             h2d50403_0    conda-forge
tblib                     1.6.0                      py_0    conda-forge
terminado                 0.8.3                    py37_0    conda-forge
testpath                  0.4.4                      py_0    conda-forge
thrift-cpp                0.12.0            hf3afdfd_1004    conda-forge
tiledb                    1.7.0                hcde45ca_2    conda-forge
tk                        8.6.10               hed695b0_0    conda-forge
toolz                     0.10.0                     py_0    conda-forge
tornado                   6.0.3            py37h516909a_0    conda-forge
traitlets                 4.3.3                    py37_0    conda-forge
trollbufr                 0.11.0                   pypi_0    pypi
trollimage                1.9.0                    pypi_0    pypi
trollsift                 0.3.2                    pypi_0    pypi
tzcode                    2019a             h516909a_1002    conda-forge
uriparser                 0.9.3                he1b5a44_1    conda-forge
urllib3                   1.25.7                   py37_0    conda-forge
uwsift                    1.0.6                    pypi_0    pypi
vispy                     0.6.4            py37hf5ce8a7_0    conda-forge
wcwidth                   0.1.8                      py_0    conda-forge
webencodings              0.5.1                      py_1    conda-forge
webob                     1.8.6                      py_0    conda-forge
wheel                     0.33.6                   py37_0    conda-forge
widgetsnbextension        3.5.1                    py37_0    conda-forge
xarray                    0.14.1                     py_0    conda-forge
xerces-c                  3.2.2             h8412b87_1004    conda-forge
xorg-kbproto              1.0.7             h14c3975_1002    conda-forge
xorg-libice               1.0.10               h516909a_0    conda-forge
xorg-libsm                1.2.3             h84519dc_1000    conda-forge
xorg-libx11               1.6.9                h516909a_0    conda-forge
xorg-libxau               1.0.9                h14c3975_0    conda-forge
xorg-libxdmcp             1.1.3                h516909a_0    conda-forge
xorg-libxext              1.3.4                h516909a_0    conda-forge
xorg-libxrender           0.9.10            h516909a_1002    conda-forge
xorg-renderproto          0.11.1            h14c3975_1002    conda-forge
xorg-xextproto            7.3.0             h14c3975_1002    conda-forge
xorg-xproto               7.0.31            h14c3975_1007    conda-forge
xz                        5.2.4             h14c3975_1001    conda-forge
yaml                      0.2.2                h516909a_1    conda-forge
zarr                      2.4.0                      py_0    conda-forge
zeromq                    4.3.2                he1b5a44_2    conda-forge
zict                      1.0.0                      py_0    conda-forge
zipp                      2.0.0                      py_2    conda-forge
zlib                      1.2.11            h516909a_1006    conda-forge
zstd                      1.4.4                h3b9ef0a_1    conda-forge
</details>

**Comment by TomAugspurger** [comment]
This is fixed on Dask master. #5815 

We'll probably do a release close to the pandas one.

**Comment by TomAugspurger** [comment]
Closing this since it's fixed on master.

We'll have a release later today.

**Comment by gerritholl** [comment]
I'm still getting the same `TypeError` using pandas 1.0.0 and dask 2.10.0, both installed today from conda-forge.  Should I open a new issue?

```bash
. /media/nas/x21324/miniconda3/etc/profile.d/conda.sh
conda create -y -c conda-forge --strict-channel-priority -n test dask=2.10.0 pandas=1.0.0
conda activate test
python mwe18.py
conda list
```

<details><summary>Contents of mwe18.py</summary>
<p>

```python
import pandas as pd
import dask.dataframe as ddf
import os
import io
import tempfile
s=""",DATE,VIS
0,2019-01-03 22:00:00,"025000,1,9,9"
1,2019-01-04 04:00:00,"025000,1,9,9"
2,2019-01-04 22:00:00,"020000,1,9,9"
3,2019-01-05 22:00:00,"000100,1,9,9"
4,2019-01-08 04:00:00,"025000,1,9,9"
"""
df1 = pd.read_csv(io.StringIO(s), dtype={"STATION": pd.StringDtype()}, parse_dates=["DATE"])
# dask's read_csv can't read from stream
with tempfile.NamedTemporaryFile(suffix=".csv", mode="w+t", encoding="ascii",
        delete=False) as ntf:
    ntf.write(s)
df2 = ddf.read_csv(ntf.name, dtype={"VIS": pd.StringDtype()}, parse_dates=["DATE"])
try:
    vis1 = df1.VIS.str.extract(r"(\d{6}),(\d),([NV9]),(\d)")
    vis2 = df2.VIS.str.extract(r"(\d{6}),(\d),([NV9]),(\d)").compute()
finally:
    os.unlink(ntf.name)
```
</p>
</details>

<details><summary>Complete output</summary>
<p>

```
Collecting package metadata (current_repodata.json): ...working... done
Solving environment: ...working... done

## Package Plan ##

  environment location: /media/nas/x21324/miniconda3/envs/test

  added / updated specs:
    - dask=2.10.0
    - pandas=1.0.0


The following NEW packages will be INSTALLED:

  _libgcc_mutex      conda-forge/linux-64::_libgcc_mutex-0.1-conda_forge
  _openmp_mutex      conda-forge/linux-64::_openmp_mutex-4.5-0_gnu
  bokeh              conda-forge/linux-64::bokeh-1.4.0-py38_0
  ca-certificates    conda-forge/linux-64::ca-certificates-2019.11.28-hecc5488_0
  certifi            conda-forge/linux-64::certifi-2019.11.28-py38_0
  click              conda-forge/noarch::click-7.0-py_0
  cloudpickle        conda-forge/noarch::cloudpickle-1.2.2-py_1
  cytoolz            conda-forge/linux-64::cytoolz-0.10.1-py38h516909a_0
  dask               conda-forge/noarch::dask-2.10.0-py_0
  dask-core          conda-forge/noarch::dask-core-2.10.0-py_0
  distributed        conda-forge/noarch::distributed-2.10.0-py_0
  freetype           conda-forge/linux-64::freetype-2.10.0-he983fc9_1
  fsspec             conda-forge/noarch::fsspec-0.6.2-py_0
  heapdict           conda-forge/noarch::heapdict-1.0.1-py_0
  jinja2             conda-forge/noarch::jinja2-2.11.0-py_0
  jpeg               conda-forge/linux-64::jpeg-9c-h14c3975_1001
  ld_impl_linux-64   conda-forge/linux-64::ld_impl_linux-64-2.33.1-h53a641e_8
  libblas            conda-forge/linux-64::libblas-3.8.0-14_openblas
  libcblas           conda-forge/linux-64::libcblas-3.8.0-14_openblas
  libffi             conda-forge/linux-64::libffi-3.2.1-he1b5a44_1006
  libgcc-ng          conda-forge/linux-64::libgcc-ng-9.2.0-h24d8f2e_2
  libgfortran-ng     conda-forge/linux-64::libgfortran-ng-7.3.0-hdf63c60_4
  libgomp            conda-forge/linux-64::libgomp-9.2.0-h24d8f2e_2
  liblapack          conda-forge/linux-64::liblapack-3.8.0-14_openblas
  libopenblas        conda-forge/linux-64::libopenblas-0.3.7-h5ec1e0e_6
  libpng             conda-forge/linux-64::libpng-1.6.37-hed695b0_0
  libstdcxx-ng       conda-forge/linux-64::libstdcxx-ng-9.2.0-hdf63c60_2
  libtiff            conda-forge/linux-64::libtiff-4.1.0-hc3755c2_3
  locket             conda-forge/noarch::locket-0.2.0-py_2
  lz4-c              conda-forge/linux-64::lz4-c-1.8.3-he1b5a44_1001
  markupsafe         conda-forge/linux-64::markupsafe-1.1.1-py38h516909a_0
  msgpack-python     conda-forge/linux-64::msgpack-python-0.6.2-py38hc9558a2_0
  ncurses            conda-forge/linux-64::ncurses-6.1-hf484d3e_1002
  numpy              conda-forge/linux-64::numpy-1.17.5-py38h95a1406_0
  olefile            conda-forge/noarch::olefile-0.46-py_0
  openssl            conda-forge/linux-64::openssl-1.1.1d-h516909a_0
  packaging          conda-forge/noarch::packaging-20.1-py_0
  pandas             conda-forge/linux-64::pandas-1.0.0-py38hb3f55d8_0
  partd              conda-forge/noarch::partd-1.1.0-py_0
  pillow             conda-forge/linux-64::pillow-7.0.0-py38hefe7db6_0
  pip                conda-forge/linux-64::pip-20.0.2-py38_0
  psutil             conda-forge/linux-64::psutil-5.6.7-py38h516909a_0
  pyparsing          conda-forge/noarch::pyparsing-2.4.6-py_0
  python             conda-forge/linux-64::python-3.8.1-h357f687_2
  python-dateutil    conda-forge/noarch::python-dateutil-2.8.1-py_0
  pytz               conda-forge/noarch::pytz-2019.3-py_0
  pyyaml             conda-forge/linux-64::pyyaml-5.3-py38h516909a_0
  readline           conda-forge/linux-64::readline-8.0-hf8c457e_0
  setuptools         conda-forge/linux-64::setuptools-45.1.0-py38_0
  six                conda-forge/linux-64::six-1.14.0-py38_0
  sortedcontainers   conda-forge/noarch::sortedcontainers-2.1.0-py_0
  sqlite             conda-forge/linux-64::sqlite-3.30.1-hcee41ef_0
  tblib              conda-forge/noarch::tblib-1.6.0-py_0
  tk                 conda-forge/linux-64::tk-8.6.10-hed695b0_0
  toolz              conda-forge/noarch::toolz-0.10.0-py_0
  tornado            conda-forge/linux-64::tornado-6.0.3-py38h516909a_0
  wheel              conda-forge/linux-64::wheel-0.34.1-py38_0
  xz                 conda-forge/linux-64::xz-5.2.4-h14c3975_1001
  yaml               conda-forge/linux-64::yaml-0.2.2-h516909a_1
  zict               conda-forge/noarch::zict-1.0.0-py_0
  zlib               conda-forge/linux-64::zlib-1.2.11-h516909a_1006
  zstd               conda-forge/linux-64::zstd-1.4.4-h3b9ef0a_1


Preparing transaction: ...working... done
Verifying transaction: ...working... done
Executing transaction: ...working... done
#
# To activate this environment, use
#
#     $ conda activate test
#
# To deactivate an active environment, use
#
#     $ conda deactivate

/media/nas/x21324/miniconda3/envs/test/lib/python3.8/site-packages/dask/dataframe/_compat.py:19: FutureWarning: pandas.util.testing is deprecated. Use the functions in the public API at pandas.testing instead.
  import pandas.util.testing as tm  # noqa: F401
Traceback (most recent call last):
  File "mwe18.py", line 21, in <module>
    vis2 = df2.VIS.str.extract(r"(\d{6}),(\d),([NV9]),(\d)").compute()
  File "/media/nas/x21324/miniconda3/envs/test/lib/python3.8/site-packages/dask/dataframe/accessor.py", line 64, in _function_map
    self._series._meta_nonempty, self._accessor_name, attr, args, kwargs
  File "/media/nas/x21324/miniconda3/envs/test/lib/python3.8/site-packages/dask/dataframe/core.py", line 344, in _meta_nonempty
    return meta_nonempty(self._meta)
  File "/media/nas/x21324/miniconda3/envs/test/lib/python3.8/site-packages/dask/utils.py", line 505, in __call__
    return meth(arg, *args, **kwargs)
  File "/media/nas/x21324/miniconda3/envs/test/lib/python3.8/site-packages/dask/dataframe/utils.py", line 578, in _nonempty_series
    data = np.array([entry, entry], dtype=dtype)
TypeError: data type not understood
# packages in environment at /media/nas/x21324/miniconda3/envs/test:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                 conda_forge    conda-forge
_openmp_mutex             4.5                       0_gnu    conda-forge
bokeh                     1.4.0                    py38_0    conda-forge
ca-certificates           2019.11.28           hecc5488_0    conda-forge
certifi                   2019.11.28               py38_0    conda-forge
click                     7.0                        py_0    conda-forge
cloudpickle               1.2.2                      py_1    conda-forge
cytoolz                   0.10.1           py38h516909a_0    conda-forge
dask                      2.10.0                     py_0    conda-forge
dask-core                 2.10.0                     py_0    conda-forge
distributed               2.10.0                     py_0    conda-forge
freetype                  2.10.0               he983fc9_1    conda-forge
fsspec                    0.6.2                      py_0    conda-forge
heapdict                  1.0.1                      py_0    conda-forge
jinja2                    2.11.0                     py_0    conda-forge
jpeg                      9c                h14c3975_1001    conda-forge
ld_impl_linux-64          2.33.1               h53a641e_8    conda-forge
libblas                   3.8.0               14_openblas    conda-forge
libcblas                  3.8.0               14_openblas    conda-forge
libffi                    3.2.1             he1b5a44_1006    conda-forge
libgcc-ng                 9.2.0                h24d8f2e_2    conda-forge
libgfortran-ng            7.3.0                hdf63c60_4    conda-forge
libgomp                   9.2.0                h24d8f2e_2    conda-forge
liblapack                 3.8.0               14_openblas    conda-forge
libopenblas               0.3.7                h5ec1e0e_6    conda-forge
libpng                    1.6.37               hed695b0_0    conda-forge
libstdcxx-ng              9.2.0                hdf63c60_2    conda-forge
libtiff                   4.1.0                hc3755c2_3    conda-forge
locket                    0.2.0                      py_2    conda-forge
lz4-c                     1.8.3             he1b5a44_1001    conda-forge
markupsafe                1.1.1            py38h516909a_0    conda-forge
msgpack-python            0.6.2            py38hc9558a2_0    conda-forge
ncurses                   6.1               hf484d3e_1002    conda-forge
numpy                     1.17.5           py38h95a1406_0    conda-forge
olefile                   0.46                       py_0    conda-forge
openssl                   1.1.1d               h516909a_0    conda-forge
packaging                 20.1                       py_0    conda-forge
pandas                    1.0.0            py38hb3f55d8_0    conda-forge
partd                     1.1.0                      py_0    conda-forge
pillow                    7.0.0            py38hefe7db6_0    conda-forge
pip                       20.0.2                   py38_0    conda-forge
psutil                    5.6.7            py38h516909a_0    conda-forge
pyparsing                 2.4.6                      py_0    conda-forge
python                    3.8.1                h357f687_2    conda-forge
python-dateutil           2.8.1                      py_0    conda-forge
pytz                      2019.3                     py_0    conda-forge
pyyaml                    5.3              py38h516909a_0    conda-forge
readline                  8.0                  hf8c457e_0    conda-forge
setuptools                45.1.0                   py38_0    conda-forge
six                       1.14.0                   py38_0    conda-forge
sortedcontainers          2.1.0                      py_0    conda-forge
sqlite                    3.30.1               hcee41ef_0    conda-forge
tblib                     1.6.0                      py_0    conda-forge
tk                        8.6.10               hed695b0_0    conda-forge
toolz                     0.10.0                     py_0    conda-forge
tornado                   6.0.3            py38h516909a_0    conda-forge
wheel                     0.34.1                   py38_0    conda-forge
xz                        5.2.4             h14c3975_1001    conda-forge
yaml                      0.2.2                h516909a_1    conda-forge
zict                      1.0.0                      py_0    conda-forge
zlib                      1.2.11            h516909a_1006    conda-forge
zstd                      1.4.4                h3b9ef0a_1    conda-forge

```

</p>
</details>

**Comment by gerritholl** [comment]
There appears to have been a regression somewhere.  If I install `panda=1.0.0rc0` from pip and dask from git master, then it works:

```bash
. /media/nas/x21324/miniconda3/etc/profile.d/conda.sh
conda create -y -c conda-forge --strict-channel-priority -n test toolz fsspec numpy pytz six python-dateutil
conda activate test
pip install pandas==1.0.0rc0 git+https://github.com/dask/dask.git
python mwe18.py
conda list
```

<details><summary>Full output</summary>
<p>

```
Collecting package metadata (current_repodata.json): ...working... done
Solving environment: ...working... done

## Package Plan ##

  environment location: /media/nas/x21324/miniconda3/envs/test

  added / updated specs:
    - fsspec
    - numpy
    - python-dateutil
    - pytz
    - six
    - toolz


The following NEW packages will be INSTALLED:

  _libgcc_mutex      conda-forge/linux-64::_libgcc_mutex-0.1-conda_forge
  _openmp_mutex      conda-forge/linux-64::_openmp_mutex-4.5-0_gnu
  ca-certificates    conda-forge/linux-64::ca-certificates-2019.11.28-hecc5488_0
  certifi            conda-forge/linux-64::certifi-2019.11.28-py38_0
  fsspec             conda-forge/noarch::fsspec-0.6.2-py_0
  ld_impl_linux-64   conda-forge/linux-64::ld_impl_linux-64-2.33.1-h53a641e_8
  libblas            conda-forge/linux-64::libblas-3.8.0-14_openblas
  libcblas           conda-forge/linux-64::libcblas-3.8.0-14_openblas
  libffi             conda-forge/linux-64::libffi-3.2.1-he1b5a44_1006
  libgcc-ng          conda-forge/linux-64::libgcc-ng-9.2.0-h24d8f2e_2
  libgfortran-ng     conda-forge/linux-64::libgfortran-ng-7.3.0-hdf63c60_4
  libgomp            conda-forge/linux-64::libgomp-9.2.0-h24d8f2e_2
  liblapack          conda-forge/linux-64::liblapack-3.8.0-14_openblas
  libopenblas        conda-forge/linux-64::libopenblas-0.3.7-h5ec1e0e_6
  libstdcxx-ng       conda-forge/linux-64::libstdcxx-ng-9.2.0-hdf63c60_2
  ncurses            conda-forge/linux-64::ncurses-6.1-hf484d3e_1002
  numpy              conda-forge/linux-64::numpy-1.17.5-py38h95a1406_0
  openssl            conda-forge/linux-64::openssl-1.1.1d-h516909a_0
  pip                conda-forge/linux-64::pip-20.0.2-py38_0
  python             conda-forge/linux-64::python-3.8.1-h357f687_2
  python-dateutil    conda-forge/noarch::python-dateutil-2.8.1-py_0
  pytz               conda-forge/noarch::pytz-2019.3-py_0
  readline           conda-forge/linux-64::readline-8.0-hf8c457e_0
  setuptools         conda-forge/linux-64::setuptools-45.1.0-py38_0
  six                conda-forge/linux-64::six-1.14.0-py38_0
  sqlite             conda-forge/linux-64::sqlite-3.30.1-hcee41ef_0
  tk                 conda-forge/linux-64::tk-8.6.10-hed695b0_0
  toolz              conda-forge/noarch::toolz-0.10.0-py_0
  wheel              conda-forge/linux-64::wheel-0.34.1-py38_0
  xz                 conda-forge/linux-64::xz-5.2.4-h14c3975_1001
  zlib               conda-forge/linux-64::zlib-1.2.11-h516909a_1006


Preparing transaction: ...working... done
Verifying transaction: ...working... done
Executing transaction: ...working... done
#
# To activate this environment, use
#
#     $ conda activate test
#
# To deactivate an active environment, use
#
#     $ conda deactivate

WARNING: pip is being invoked by an old script wrapper. This will fail in a future version of pip.
Please see https://github.com/pypa/pip/issues/5599 for advice on fixing the underlying issue.
To avoid this problem you can invoke Python with '-m pip' instead of running pip directly.
Collecting git+https://github.com/dask/dask.git
  Cloning https://github.com/dask/dask.git to ./pip-req-build-_zwz8gjc
  Running command git clone -q https://github.com/dask/dask.git /tmp/pip-req-build-_zwz8gjc
Collecting pandas==1.0.0rc0
  Using cached pandas-1.0.0rc0-cp38-cp38-manylinux1_x86_64.whl (9.9 MB)
Requirement already satisfied: numpy>=1.13.3 in /media/nas/x21324/miniconda3/envs/test/lib/python3.8/site-packages (from pandas==1.0.0rc0) (1.17.5)
Requirement already satisfied: pytz>=2017.2 in /media/nas/x21324/miniconda3/envs/test/lib/python3.8/site-packages (from pandas==1.0.0rc0) (2019.3)
Requirement already satisfied: python-dateutil>=2.6.1 in /media/nas/x21324/miniconda3/envs/test/lib/python3.8/site-packages (from pandas==1.0.0rc0) (2.8.1)
Requirement already satisfied: six>=1.5 in /media/nas/x21324/miniconda3/envs/test/lib/python3.8/site-packages (from python-dateutil>=2.6.1->pandas==1.0.0rc0) (1.14.0)
Building wheels for collected packages: dask
  Building wheel for dask (setup.py): started
  Building wheel for dask (setup.py): finished with status 'done'
  Created wheel for dask: filename=dask-2.10.0-py3-none-any.whl size=783250 sha256=41c6030e6137d6fb183de37c73f8d4cf80cce913c0ff9f33dcfb420db0a6446a
  Stored in directory: /tmp/pip-ephem-wheel-cache-do8cuzdq/wheels/93/4a/fc/9aafb91155771fde2b4f6030b4fb192828363aa6f17e1d6708
Successfully built dask
Installing collected packages: pandas, dask
Successfully installed dask-2.10.0 pandas-1.0.0rc0
# packages in environment at /media/nas/x21324/miniconda3/envs/test:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                 conda_forge    conda-forge
_openmp_mutex             4.5                       0_gnu    conda-forge
ca-certificates           2019.11.28           hecc5488_0    conda-forge
certifi                   2019.11.28               py38_0    conda-forge
dask                      2.10.0                   pypi_0    pypi
fsspec                    0.6.2                      py_0    conda-forge
ld_impl_linux-64          2.33.1               h53a641e_8    conda-forge
libblas                   3.8.0               14_openblas    conda-forge
libcblas                  3.8.0               14_openblas    conda-forge
libffi                    3.2.1             he1b5a44_1006    conda-forge
libgcc-ng                 9.2.0                h24d8f2e_2    conda-forge
libgfortran-ng            7.3.0                hdf63c60_4    conda-forge
libgomp                   9.2.0                h24d8f2e_2    conda-forge
liblapack                 3.8.0               14_openblas    conda-forge
libopenblas               0.3.7                h5ec1e0e_6    conda-forge
libstdcxx-ng              9.2.0                hdf63c60_2    conda-forge
ncurses                   6.1               hf484d3e_1002    conda-forge
numpy                     1.17.5           py38h95a1406_0    conda-forge
openssl                   1.1.1d               h516909a_0    conda-forge
pandas                    1.0.0rc0                 pypi_0    pypi
pip                       20.0.2                   py38_0    conda-forge
python                    3.8.1                h357f687_2    conda-forge
python-dateutil           2.8.1                      py_0    conda-forge
pytz                      2019.3                     py_0    conda-forge
readline                  8.0                  hf8c457e_0    conda-forge
setuptools                45.1.0                   py38_0    conda-forge
six                       1.14.0                   py38_0    conda-forge
sqlite                    3.30.1               hcee41ef_0    conda-forge
tk                        8.6.10               hed695b0_0    conda-forge
toolz                     0.10.0                     py_0    conda-forge
wheel                     0.34.1                   py38_0    conda-forge
xz                        5.2.4             h14c3975_1001    conda-forge
zlib                      1.2.11            h516909a_1006    conda-forge
```
</p>
</details>
